<div class="annex-eyebrow">Annexe au Contrat de service de Personne Responsable</div>
<h1 style="font-size: 16px;">Conditions Générales</h1>

<h2>1. Parties</h2>
<p><strong>Prestataire de services :</strong> Festilaw B.V., société constituée selon le droit néerlandais, agissant en qualité de « Personne Responsable » au sens de la réglementation de l'UE relative à la sécurité des produits.</p>
<p><strong>Client :</strong> ci-après le « Client » ou la « Société ».</p>
<p>Désignés ensemble les « Parties ».</p>

<h2>2. Désignation et étendue des services</h2>
<p><strong>2.1</strong>&nbsp;&nbsp;Désignation de la Personne Responsable : le Client désigne Festilaw comme sa Personne Responsable pour l'Union européenne à l'égard des produits de consommation vendus dans l'UE, ainsi que l'exige le Règlement (UE) 2023/988 relatif à la sécurité générale des produits (GPSR). Festilaw accepte cette désignation. Le présent Contrat vaut mandat écrit autorisant Festilaw à agir en qualité de représentant autorisé du Client dans l'UE, conformément à l'article 4 du Règlement (UE) 2019/1020 (pour les produits harmonisés) et au GPSR pour les produits de consommation non harmonisés.</p>
<p><strong>2.2</strong>&nbsp;&nbsp;Étendue des services : Festilaw exécutera les missions suivantes en qualité de Personne Responsable, telles qu'imposées par le droit de l'UE :</p>
<p><strong>2.2.1</strong>&nbsp;&nbsp;Assurance de la conformité des produits : vérifier que chaque produit du Client, ou certains produits spécifiques, destiné aux consommateurs de l'UE satisfait aux exigences de sécurité applicables de l'UE au titre du GPSR. Cela suppose une surveillance générale attestant que les produits ont fait l'objet des évaluations des risques requises et respectent les normes de sécurité pertinentes. (Remarque : Festilaw ne procédera pas elle-même à des essais sur les produits ni à la certification de leur conformité, mais s'appuiera sur la documentation et les assurances fournies par le Client.)</p>
<p><strong>2.2.2</strong>&nbsp;&nbsp;Coordonnées de contact dans l'UE : fournir une adresse de contact dans l'UE (physique) ainsi qu'une adresse électronique (par exemple un courriel) pour les demandes des consommateurs et des autorités, ainsi que l'exige le droit de l'UE. Le nom et l'adresse de Festilaw dans l'UE figureront sur les étiquettes, l'emballage ou la documentation d'accompagnement des produits du Client, ainsi que sur le site internet du Client si nécessaire, afin de satisfaire à l'exigence légale selon laquelle une Personne Responsable établie dans l'UE doit pouvoir être identifiée par les consommateurs et les autorités de réglementation. Festilaw informera sans délai le Client de toute modification de ces coordonnées de contact.</p>
<p><strong>2.2.3</strong>&nbsp;&nbsp;Liaison avec les autorités et surveillance du marché : agir en tant que point de contact pour les autorités de surveillance du marché de l'UE, notamment en répondant aux demandes des organismes de réglementation et en facilitant la communication. Festilaw coopérera avec les autorités lors des enquêtes ou des contrôles de sécurité en fournissant les informations et la documentation requises. Si une autorité de l'UE demande des informations complémentaires sur un produit ou soulève une objection à son égard, Festilaw en informera le Client et coordonnera une réponse dans les délais. Le Client doit assister Festilaw dans ces démarches (voir la Section 4.2 relative aux délais de réponse).</p>
<p><strong>2.2.4</strong>&nbsp;&nbsp;Assistance en matière d'incidents et de rappels : assister en cas d'incidents de sécurité des produits, de rappels et de notifications. Si un produit du Client s'avère présenter des risques ou est jugé dangereux, Festilaw conseillera sur les mesures de mise en conformité et aidera à notifier les autorités via le système d'alerte Safety Gate de l'UE (Safety Business Gateway). Festilaw notifiera les autorités sans retard injustifié de tout risque grave, ainsi que l'exige la loi. En pareil cas, Festilaw aidera également à préparer, en coopération avec le Client, tout avis de rappel public ou plan de mesures correctives requis. Le Client demeure responsable de l'exécution des rappels (par exemple le retrait ou la réparation des produits), mais doit y procéder selon les directives de Festilaw et conformément aux ordres des autorités (voir la Section 4.3).</p>
<p><strong>2.2.5</strong>&nbsp;&nbsp;Contrôle des étiquettes et de l'emballage (limité) : Festilaw vérifiera que les étiquettes et l'emballage des produits du Client comportent les informations légalement requises (par exemple les coordonnées de Festilaw en tant que Personne Responsable, le nom et l'adresse du fabricant, les identifiants du produit, ainsi que tout avertissement requis). Important : la prestation standard de Festilaw ne comprend pas un examen réglementaire complet de l'ensemble du contenu des étiquettes ou des allégations commerciales. Il incombe au Client de veiller à ce que les étiquettes, les notices d'utilisation et les emballages respectent l'ensemble de la réglementation de l'UE applicable en matière d'étiquetage (au-delà de la présence des coordonnées de la Personne Responsable), à moins que le Client ne confie séparément de tels services à Festilaw ou à un autre expert. (Cette exclusion est détaillée à la Section 5.4.)</p>
<p><strong>2.2.6</strong>&nbsp;&nbsp;Vérification annuelle des accès : Festilaw organisera une réunion ou un examen annuel avec le Client afin d'évaluer les données produit pertinentes. Au cours de cet examen, Festilaw et le Client examineront les ventes réalisées dans l'UE et sélectionneront de un (1) à cinq (5) produits à titre d'échantillon afin de confirmer que la documentation technique requise est aisément disponible et à jour. Lorsque cela est nécessaire pour remplir ses obligations de Personne Responsable dans l'UE et pour démontrer sa diligence à l'égard des autorités de surveillance du marché, Festilaw peut conserver une copie de la documentation technique du Client pendant une durée pouvant aller jusqu'à dix (10) ans après la résiliation ou l'expiration du présent Contrat, conformément à la réglementation de l'UE applicable en matière de sécurité des produits. Festilaw veillera à mettre en œuvre des mesures techniques et organisationnelles appropriées pour protéger la confidentialité, l'intégrité et la sécurité de la documentation conservée.</p>
<p><strong>2.2.7</strong>&nbsp;&nbsp;Vérification des moyens de communication : Festilaw vérifiera que l'adresse électronique du service client désignée par le Client et les mécanismes de contact (en particulier le courriel imprimé sur l'emballage ou indiqué sur le site internet du Client à destination des consommateurs de l'UE) sont fonctionnels et surveillés. Cela garantit que, si les autorités de l'UE ou les consommateurs adressent des demandes relatives à la sécurité ou des communications urgentes (par exemple en cas de rappel de produit), celles-ci parviendront au bon interlocuteur. Festilaw testera ces points de contact une fois par an et confirmera au Client qu'ils fonctionnent correctement en vue d'une communication rapide.</p>
<p><strong>2.2.8</strong>&nbsp;&nbsp;Traitement des questions des consommateurs ordinaires. Les coordonnées de contact de Festilaw dans l'UE seront affichées sur l'emballage et en ligne ; toute demande de consommateur reçue par ces canaux sera rapidement enregistrée et transmise par Festilaw, et le Client veillera à y apporter des réponses exactes et rapides conformément au droit de la consommation de l'UE (Festilaw n'exploite pas de ligne d'assistance aux consommateurs au-delà de cette fonction de transmission). Jusqu'à 2 heures par an de cette assistance sont fournies à titre gratuit.</p>

<h2>3. Honoraires, paiement et services complémentaires</h2>
<p><strong>3.1</strong>&nbsp;&nbsp;Honoraires annuels : le Client versera des honoraires annuels au titre des services de Personne Responsable. Ces honoraires sont exigibles et payables dans les 30 jours suivant la facture. L'année de service court toujours du 1er janvier au 31 décembre. Si le Client démarre le service en cours d'année civile plutôt que le 1er janvier, la première facture sera établie au prorata, couvrant uniquement les mois restants de cette année civile jusqu'au 31 décembre (par exemple, un Client démarrant en juillet sera facturé pour six (6) mois). Festilaw émettra ensuite une nouvelle facture correspondant aux honoraires annuels complets en janvier de chaque année suivante. Les honoraires couvrent tous les éléments essentiels du rôle de Personne Responsable tel que décrit dans le présent Contrat, notamment :</p>
<p>La mise à disposition de l'adresse physique et de l'adresse électronique de Festilaw dans l'UE aux fins de l'étiquetage des produits et de leur mention sur le site internet (afin de satisfaire à l'exigence de l'UE de fournir un contact dans l'UE) : cela comprend l'autorisation pour le Client d'imprimer le nom et les coordonnées de Festilaw sur l'emballage, les notices produit et le site internet du Client destiné à l'UE.</p>
<p>La réunion annuelle d'accès et le contrôle de la documentation (Section 2.2) ainsi qu'un bref rapport relatif à ce contrôle. Le bref rapport n'est fourni qu'aux sociétés dont le catalogue de produits dépasse 100 SKUs.</p>
<p>L'inclusion du nom et de l'adresse de Festilaw sur le site internet et les supports du Client, dans la mesure nécessaire à la conformité réglementaire dans l'UE (Festilaw fournira les formulations ou les fichiers requis le cas échéant, par exemple un certificat de « Personne Responsable dans l'UE » ou des informations destinées au site).</p>
<p>La vérification de la configuration des moyens de contact (Section 2.2, Vérification des moyens de communication) afin de garantir que les communications relatives aux rappels parviendraient à la bonne personne.</p>
<p>Jusqu'à 2 heures d'assistance / de traitement de base des questions des consommateurs ordinaires telles que décrites ci-dessus [service 2.2.8].</p>
<p>Festilaw confirme qu'elle ne stockera ni ne conservera les données produit confidentielles du Client au-delà de ce qui est nécessaire aux services précités. Festilaw conservera des copies de l'ensemble de la documentation technique et des dossiers de conformité relatifs aux produits du Client pendant une durée de dix (10) ans suivant la résiliation ou l'expiration du présent Contrat, conformément à la réglementation de l'UE applicable en matière de sécurité des produits et à ses obligations en tant que Personne Responsable dans l'UE.</p>
<p><strong>3.2</strong>&nbsp;&nbsp;Honoraires au tarif horaire : si le Client requiert ou sollicite une assistance dépassant l'étendue du service annuel (par exemple la gestion d'un rappel de produit complexe, une correspondance étendue avec les autorités, ou des consultations de conformité supplémentaires au-delà des 2 heures incluses), ces services complémentaires seront facturés aux tarifs horaires suivants :</p>
<p>Assistance senior : EUR €145 de l'heure [table 3.1] (par exemple pour que les experts senior en conformité de Festilaw interagissent avec les représentants des pouvoirs publics, gèrent des communications de haut niveau avec les autorités ou pilotent la réponse à un incident grave).</p>
<p>Assistance junior : EUR €100 de l'heure [table 3.1] (par exemple pour des tâches plus courantes telles que la rédaction de réponses aux questions des consommateurs, des recherches de base sur la réglementation, ou d'autres activités d'assistance de niveau junior).</p>
<p>Festilaw obtiendra la confirmation du Client avant d'effectuer tout travail complémentaire facturable. Le Client sera facturé pour l'assistance complémentaire à la fin du mois au cours duquel elle a été fournie (ou à l'achèvement d'une mission d'assistance liée à un incident spécifique), avec un relevé détaillé du temps passé. Le paiement est exigible dans les 30 jours suivant la facture.</p>
<p><strong>3.3</strong>&nbsp;&nbsp;Ajustements de prix : les honoraires annuels et les tarifs horaires peuvent être ajustés par Festilaw chaque année au 1er janvier. Le Client recevra un préavis écrit 30 jours avant toute modification de prix applicable à une période de renouvellement. Si le Client conteste le prix ajusté, il peut résilier le Contrat à l'issue de la période en cours en adressant un préavis écrit (conformément à la Section 7.2), à défaut de quoi les nouveaux prix s'appliqueront à la période de renouvellement suivante.</p>
<p><strong>3.4</strong>&nbsp;&nbsp;Tableau des services et des paiements</p>
<p>Ci-dessous figure la spécification des Services. Festilaw n'assume aucune responsabilité pour les activités non expressément incluses dans les Services acquis par le Client et payées à ce titre. Il relève de la seule appréciation du Client de décider des services complémentaires auxquels il recourt. Toute non-conformité au droit de l'UE relative aux produits ou aux activités du Client demeure entièrement aux risques et sous la responsabilité du Client.</p>
<table class="terms">
    <thead>
        <tr><th style="width: 22%;">Service</th><th>Honoraires, paiement</th></tr>
    </thead>
    <tbody>
        <tr><td>2.2.1</td><td>Assistance senior au tarif horaire sur demande.</td></tr>
        <tr><td>2.2.2</td><td>Honoraires annuels</td></tr>
        <tr><td>2.2.3</td><td>Assistance senior au tarif horaire sur demande.</td></tr>
        <tr><td>2.2.4</td><td>Assistance senior au tarif horaire sur demande.</td></tr>
        <tr><td>2.2.5</td><td>Assistance senior au tarif horaire sur demande.</td></tr>
        <tr><td>2.2.6</td><td>Honoraires annuels</td></tr>
        <tr><td>2.2.7</td><td>Honoraires annuels</td></tr>
        <tr><td>2.2.8</td><td>Honoraires junior au tarif horaire / 2 heures par an sont comprises dans les honoraires annuels.</td></tr>
    </tbody>
</table>

<h2>4. Obligations du Client (responsabilités du Client)</h2>
<p>Le Client s'engage à remplir les obligations suivantes, afin de permettre à Festilaw d'exercer efficacement ses missions de Personne Responsable et dans le respect de la loi :</p>
<p><strong>4.1</strong>&nbsp;&nbsp;Respect du droit de l'UE : le Client garantit que ses produits et ses activités commerciales sont conformes à l'ensemble du droit européen applicable en matière de protection des consommateurs et de réglementation des produits, notamment mais sans s'y limiter :</p>
<p>Le Règlement (UE) 2023/988 relatif à la sécurité générale des produits, ainsi que toute directive ou tout règlement spécifique aux produits pertinent pour les produits du Client. Le Client confirme qu'il a réalisé les évaluations des risques de sécurité des produits nécessaires et qu'il a établi la documentation technique requise pour ses produits, ainsi que l'impose le droit de l'UE.</p>
<p>La Directive 2011/83/UE relative aux droits des consommateurs et les législations connexes en matière de protection des consommateurs, dans la mesure où elles sont applicables (par exemple, si le Client vend directement aux consommateurs de l'UE par commerce électronique, il respectera les droits des consommateurs tels que l'information précontractuelle claire et le délai de rétractation (délai de réflexion) de 14 jours pour les achats en ligne).</p>
<p>L'ensemble des autres réglementations de l'UE pertinentes en matière de commerce électronique et des législations spécifiques aux produits. Cela comprend la réglementation relative aux substances chimiques et aux matériaux utilisés dans les produits (le Client garantit qu'aucune substance interdite par les directives ou règlements de l'UE n'est intentionnellement utilisée dans ses produits, et qu'il respecte les restrictions de l'UE relatives aux substances dangereuses), ainsi que le respect des règles en matière de publicité loyale, de garantie et de responsabilité du fait des produits.</p>
<p>Accès à la documentation technique : détenir ou avoir un accès immédiat à la documentation technique de chaque produit (par exemple les rapports d'essais de sécurité, les dossiers techniques, les Déclarations de Conformité) afin de vérifier la conformité. Festilaw doit être en mesure de fournir cette documentation aux autorités des États membres de l'UE sur demande. Le Client fournira à Festilaw des dossiers techniques complets et à jour pour tous les produits vendus dans l'UE (voir les obligations du Client à la Section 4).</p>
<p>En signant le présent Contrat, le Client confirme qu'il a connaissance des lois précitées et de leurs éventuelles mises à jour et qu'il les respectera. Le Client fournira à Festilaw, sur demande, des éléments de preuve de conformité (tels que des rapports d'essais, des certificats ou des rapports d'examen) afin d'étayer ces garanties. Si le Client a connaissance d'une non-conformité ou d'une infraction liée à ses produits (par exemple la découverte d'une substance chimique interdite dans un produit, ou d'un danger pour la sécurité), il en informera immédiatement Festilaw et prendra des mesures correctives. Si Festilaw a connaissance d'une non-conformité ou d'une infraction, cela peut impliquer que Festilaw doive notifier les autorités via le système d'alerte Safety Gate de l'UE.</p>
<p><strong>4.2</strong>&nbsp;&nbsp;Fourniture d'informations et de documentation : le Client fournira à Festilaw l'ensemble des informations et du soutien nécessaires à l'exercice de son rôle :</p>
<p>Liste des produits et mises à jour : un aperçu de tous les produits du Client vendus ou destinés à être vendus dans l'UE, comprenant les noms/SKUs des produits, leurs descriptions ainsi que tout numéro de modèle ou identifiant. Le Client remettra une liste initiale lors de la signature du présent Contrat. Par la suite, le Client devra tenir Festilaw informée (au moins sur une base trimestrielle) de toute modification, par exemple les nouveaux produits introduits sur le marché de l'UE ou les produits retirés. Cela garantit que Festilaw connaît toujours les articles dont elle est responsable.</p>
<p>Documentation technique : pour chaque produit, le Client fournira ou mettra à disposition la documentation technique de conformité (telle que définie par le droit de l'UE). Cela comprend généralement la documentation de sécurité ou de conformité du produit (par exemple les rapports d'essais, le dossier de conformité relatif à la sécurité générale des produits, toute Déclaration de Conformité CE applicable, l'évaluation des risques, etc.). Le Client peut soit fournir des copies de ces fichiers à Festilaw, soit veiller à ce qu'ils puissent être consultés rapidement sur demande. Si le Client préfère ne pas communiquer à l'avance l'intégralité des dossiers techniques, il doit à tout le moins en attester l'existence, en fournir un résumé du contenu et les communiquer immédiatement à la demande de Festilaw ou d'une autorité.</p>
<p>Réponses dans les délais (Safety Gate et autorités) : le Client est responsable d'une coopération dans les délais pour toute demande de conformité ou tout incident. Si Festilaw notifie au Client une demande d'informations émanant d'une autorité de l'UE ou la nécessité de signaler un incident via le Safety Business Gateway, le Client répondra et fournira sans délai toutes les informations requises. En particulier, le Client doit respecter tout délai fixé par Festilaw qui tient compte des délais de réponse légaux, diminués de quatre (4) jours ouvrables. Cette marge permet à Festilaw d'examiner et de transmettre les informations dans le délai officiel. Par exemple, si le droit de l'UE ou une autorité exige une réponse ou une documentation dans un délai de 10 jours ouvrables, Festilaw demandera au Client de fournir les éléments nécessaires dans un délai de 6 jours ouvrables ; à défaut, le Client sera en violation du présent Contrat. En pareil cas, le Client sera redevable d'une pénalité de EUR €500 par jour, dans la limite d'un maximum de €15,000 par incident, pour chaque jour ouvrable de retard au-delà de la date demandée pendant lequel l'information est retardée, jusqu'à ce que l'information soit fournie. Cette pénalité reflète les conséquences potentiellement graves d'un retard de mise en conformité (amendes ou perturbations de l'activité) et vise à inciter à agir en urgence. Festilaw peut, à sa discrétion, renoncer à la pénalité ou la réduire si le retard n'entraîne pas en définitive de non-conformité ou en présence de circonstances atténuantes, mais se réserve le droit de la faire appliquer.</p>
<p>Signalement des accidents et des dangers : le Client doit informer Festilaw immédiatement (au plus tard dans un délai de 2 jours calendaires) s'il a connaissance d'un incident grave, d'un accident ou d'un problème de sécurité impliquant un produit sur le marché de l'UE (par exemple une blessure d'un consommateur, une réclamation de sécurité suggérant un défaut du produit, ou tout événement de nature à déclencher une obligation de notification aux autorités de réglementation). Le droit de l'UE impose aux fabricants de « notifier immédiatement » les produits dangereux et, « sans retard injustifié », tout accident grave causé par un produit. Par conséquent, le Client fournira à Festilaw tous les détails de l'incident ainsi que les données pertinentes dans les meilleurs délais, afin que Festilaw puisse aider à notifier les autorités via le Safety Business Gateway et à prendre les mesures appropriées. Tout manquement délibéré ou négligent du Client à signaler de tels problèmes à Festilaw sera considéré comme une violation substantielle du présent Contrat.</p>
<p><strong>4.3</strong>&nbsp;&nbsp;Coopération en matière de rappels et de mesures correctives : dans l'hypothèse où un produit du Client serait jugé dangereux ou non conforme par une autorité compétente ou d'un commun accord entre les Parties :</p>
<p>Exécution du rappel : le Client s'engage à coopérer et à exécuter sans délai toute mesure corrective ou tout rappel nécessaire à la protection des consommateurs, que ces mesures soient imposées par une autorité ou engagées volontairement. Si une autorité de surveillance du marché de l'UE ordonne un rappel obligatoire ou une interdiction de vente pour un produit, le Client s'y conformera sans délai, ainsi que l'exige la loi. Le Client assurera la logistique du retrait ou du rappel des produits du marché, y compris la coordination avec les distributeurs, les détaillants et les clients selon les besoins. Festilaw apportera son concours en fournissant des orientations, des communications officielles aux autorités de réglementation, et en étant désignée comme point de contact des autorités sur les avis de rappel. Selon le GPSR, dès lors que les fabricants ont connaissance de risques de sécurité, ils doivent agir sans délai (y compris par le retrait ou le rappel du produit) et informer les autorités via le système d'alerte Safety Gate. La coopération diligente du Client constitue à la fois une obligation légale et une clause du présent contrat.</p>
<p>Communication publique et voies de recours : le Client rédigera ou finalisera les avis de rappel destinés aux consommateurs en coopération avec Festilaw (en veillant à ce qu'ils respectent les modèles types et le contenu requis par la Commission européenne ou le droit national). Tout avis de ce type inclura les coordonnées de Festilaw ainsi qu'il est requis et sera examiné par Festilaw avant publication afin d'en assurer la cohérence avec les informations communiquées aux autorités. Le Client offrira aux consommateurs les voies de recours appropriées (réparation, remplacement, remboursement, etc.) telles qu'exigées par le droit de l'UE pour les produits rappelés. Les coûts du rappel (y compris les remboursements ou réparations et tout avis public) sont à la charge du Client (sauf dans la mesure où le rappel résulterait exclusivement de la négligence ou d'un manquement de Festilaw).</p>
<p>Mesures préventives et de suivi : le Client enquêtera sur la cause profonde du problème de sécurité et mettra en œuvre des mesures visant à prévenir toute récurrence. Le Client tiendra Festilaw informée des conclusions de l'enquête et des mesures correctives. Si les autorités exigent des rapports de suivi (par exemple sur l'état d'avancement du rappel, la destruction des articles retournés), le Client fournira les informations nécessaires pour que Festilaw les relaie. Le Client s'engage également à coopérer à toute action de rappel « imposée » par les autorités, en ce sens que si, par exemple, une autorité ordonne directement certaines mesures (telles que des avertissements publics, des saisies de produits, etc.), le Client ne s'y opposera pas et soutiendra activement ces mesures.</p>
<p><strong>4.4</strong>&nbsp;&nbsp;Responsabilités et reconnaissances supplémentaires :</p>
<p>Absence de substances illégales : le Client garantit que ses produits ne contiennent aucune substance interdite par la réglementation de l'UE en matière de substances chimiques ou de sécurité. Par exemple, le Client confirme qu'il n'utilise pas de matériaux qui enfreignent le règlement REACH de l'UE ou d'autres directives limitant les substances dans les biens de consommation. Cette garantie est essentielle compte tenu des règles de l'UE relatives à la sécurité chimique des produits de consommation (telles que l'interdiction de certains phtalates, métaux lourds ou autres substances chimiques toxiques dans les biens de consommation). Si un composant d'un produit est réglementé (par exemple des restrictions relatives aux piles, etc.), le Client confirme également le respect de ces règles spécifiques.</p>
<p>Respect du droit de la consommation : si le Client vend directement aux consommateurs dans l'UE (via un site internet ou d'autres ventes directes), il confirme qu'il agit conformément au droit de l'UE en matière de protection des consommateurs. Cela inclut la fourniture d'informations claires sur les produits, le respect des droits des consommateurs tels que les retours et les remboursements, et l'absence de pratiques déloyales ou trompeuses. Le Client reconnaît que le non-respect du droit de la protection des consommateurs peut entraîner des sanctions ou une atteinte à sa réputation, et affirme qu'il dispose de systèmes lui permettant de rester en conformité.</p>
<p>Mises à jour relatives aux évolutions réglementaires : il incombe au Client de se tenir informé de toute évolution de la réglementation de l'UE spécifique à ses produits (Festilaw fournissant des orientations raisonnables si elle a connaissance de telles évolutions, en particulier celles affectant le rôle de Personne Responsable). Si une nouvelle loi ou norme de l'UE impose des exigences supplémentaires aux produits (par exemple un nouvel étiquetage, l'interdiction d'une certaine substance, une nouvelle exigence de documentation, etc.), le Client prendra les mesures nécessaires pour s'y conformer et informera Festilaw de la manière dont la conformité est assurée.</p>
<p>Contacts désignés : le Client désignera une personne de contact principale (ainsi qu'un suppléant) qui assurera la liaison avec Festilaw. Ces personnes devront être habilitées à prendre des décisions ou à en obtenir rapidement au sein de l'organisation du Client en cas de question urgente de conformité. Le Client veillera à ce qu'au moins un contact soit joignable à bref délai (dans un délai d'un jour ouvrable) pour toute communication urgente de sécurité émanant de Festilaw.</p>

<h2>5. Limitations du service et de la responsabilité</h2>
<p><strong>5.1</strong>&nbsp;&nbsp;Festilaw non responsable des défauts des produits ou des dommages aux consommateurs : le rôle de Festilaw se limite strictement à celui de représentant en matière de conformité et de point de contact dans l'UE. Les Parties conviennent que Festilaw n'est ni le fabricant ni l'importateur des produits et n'assume pas la responsabilité du fait des produits incombant au fabricant. Le Client conserve l'entière responsabilité de la sécurité et de la conformité des produits. En conséquence, Festilaw ne pourra être tenue responsable d'aucun dommage aux biens ni d'aucune atteinte à l'intégrité physique des personnes (y compris le décès) résultant de défauts ou de l'utilisation des produits du Client, sauf dans la mesure où un tel dommage serait directement causé par la faute lourde ou la faute intentionnelle de Festilaw elle-même. Cela signifie que si des consommateurs ou d'autres tiers formulent des réclamations relatives aux produits (par exemple une blessure résultant de l'utilisation d'un produit), le Client supportera l'ensemble de la responsabilité et des coûts, et si Festilaw est mise en cause ou impliquée en raison de son rôle, le Client garantira Festilaw (voir la Section 5.3). Les missions de Festilaw se limitent à celles d'une Personne Responsable telles que prévues par le présent Contrat et le droit applicable ; Festilaw n'assure pas de contrôle qualité général, de supervision de la fabrication ni d'assurance contre les risques liés aux produits.</p>
<p><strong>5.2</strong>&nbsp;&nbsp;Limitation de la responsabilité de Festilaw : dans toute la mesure permise par la loi, si la responsabilité de Festilaw est engagée envers le Client au titre d'une réclamation découlant du présent Contrat (qu'elle soit de nature contractuelle, délictuelle ou autre), la responsabilité globale maximale de Festilaw sera limitée à un montant n'excédant pas les honoraires annuels acquittés par le Client pour l'année contractuelle en cours (à savoir les honoraires annuels de {{ $fee }} €). Festilaw ne sera en aucun cas responsable des dommages indirects, consécutifs ou punitifs, tels que les pertes de profits, les pertes de ventes ou l'atteinte à la réputation, même si elle a été avertie de l'éventualité de tels dommages. Les Parties reconnaissent que les honoraires annuels sont fixés en considération de ce plafond de responsabilité. Festilaw n'est pas un assureur et ne peut assumer un risque illimité en contrepartie d'honoraires de service symboliques. Le Client accepte de souscrire, selon les besoins, une assurance appropriée couvrant la responsabilité du fait des produits et les autres risques.</p>
<p>Justification : la limitation ci-dessus constitue une condition essentielle de l'accord de Festilaw de fournir ses services. Les deux Parties conviennent que la réparation susceptible d'être obtenue par le Client en cas de manquement ou d'erreur de Festilaw est limitée et raisonnable compte tenu de la nature des services. En tout état de cause, toute réclamation du Client à l'encontre de Festilaw pour manquement ou négligence doit être formée dans un délai de 90 jours à compter du moment où le Client a eu connaissance de l'événement donnant lieu à la réclamation, et au plus tard 1 an à compter de cet événement. Si le Client ne notifie pas à Festilaw une réclamation ou un problème potentiel dans un délai de 90 jours à compter de sa découverte, il renonce à son droit de réclamer au titre de ce problème. (Cette exigence de notification de 90 jours garantit une résolution dans les délais et permet à Festilaw de tenter d'atténuer tout préjudice.)</p>
<p><strong>5.3</strong>&nbsp;&nbsp;Garantie (indemnisation) : le Client s'engage à garantir et à tenir indemnes Festilaw ainsi que ses dirigeants, employés et mandataires de l'ensemble des pertes, dommages, responsabilités, amendes, pénalités, coûts et dépenses (y compris les frais de justice raisonnables) découlant de ou liés à toute réclamation de tiers ou action réglementaire se rapportant aux produits du Client ou à la violation par le Client de ses obligations. Cette garantie couvre, par exemple : le cas où une autorité nationale infligerait une amende à Festilaw ou engagerait une action en justice en raison du caractère dangereux ou non conforme d'un produit du Client (sauf si cela résulte du fait que Festilaw n'a pas transmis des informations que le Client lui avait fournies), ou le cas où un consommateur poursuivrait Festilaw en alléguant une blessure causée par un produit. Le Client interviendra pour assumer la défense et acquittera tout montant en résultant. Le Client garantit également Festilaw de tout préjudice causé par le défaut du Client de fournir en temps utile des informations exactes (par exemple, si Festilaw encourt des pénalités pour non-respect d'un délai de notification en raison d'un retard ou d'une rétention d'informations par le Client). Festilaw notifiera sans délai au Client toute réclamation ou action dont elle a connaissance, et permettra au Client d'en assurer la défense (avec la coopération raisonnable de Festilaw). La présente clause survit à la résiliation du Contrat.</p>
<p><strong>5.4</strong>&nbsp;&nbsp;Services exclus : les Parties reconnaissent que le service de Personne Responsable de Festilaw est axé sur le soutien à la conformité réglementaire et n'inclut pas d'autres services de conseil relatifs aux produits ou à l'activité, sauf convention contraire écrite. Sauf accord distinct (ou recours à des heures supplémentaires au titre de la Section 3.2), Festilaw n'est pas responsable de :</p>
<p>Essais ou certification des produits : Festilaw ne procédera pas à des essais sur les produits en matière de sécurité ou de conformité, ni n'obtiendra de certificats (tels que les certificats CE) pour le compte du Client. Ces tâches demeurent celles du Client (Festilaw pouvant toutefois recommander des laboratoires ou des organismes de certification si elle en est priée).</p>
<p>Examens complets des étiquettes/emballages : le contrôle des étiquettes par Festilaw se limite à vérifier la présence des coordonnées de contact requises et des marquages de sécurité manifestes. Festilaw n'examine pas les visuels, les allégations commerciales ni les traductions figurant sur les étiquettes quant à leur exactitude juridique. Le Client devrait faire appel à des experts en conformité pour un examen complet des étiquettes en cas de besoin.</p>
<p>Conformité juridique en dehors de la sécurité des produits de consommation de l'UE : le rôle de Festilaw est lié à la conformité en matière de sécurité des produits de consommation de l'UE. Les autres domaines juridiques, par exemple la conformité en matière de protection des données (RGPD), les questions fiscales/de TVA, les obligations juridiques générales des sociétés, etc., n'entrent pas dans le champ du présent Contrat.</p>
<p>Traitement des demandes ou réclamations des consommateurs : Festilaw n'exploite ni centre d'appels ni service client pour le compte du Client. Bien que les coordonnées de Festilaw puissent figurer sur les produits pour des raisons réglementaires, toute demande de consommateur reçue par Festilaw sera transmise au Client. Il incombe au Client de répondre aux consommateurs (Festilaw pouvant aider à rédiger des réponses relatives à la sécurité, si cela relève des heures d'assistance incluses ou à titre facturable).</p>
<p>Droits de douane/importation : Festilaw n'agit pas en qualité d'importateur officiel. Il appartient au Client ou à ses prestataires logistiques de veiller au passage des produits en douane (au-delà de la fourniture des informations requises relatives à la Personne Responsable). Si les autorités douanières contactent Festilaw, celle-ci les orientera vers l'agent d'importation du Client.</p>
<p>Si le Client souhaite bénéficier de l'un des services précités de la part de Festilaw, les Parties devront négocier un accord ou un avenant distinct (avec d'éventuels honoraires supplémentaires). En précisant ces exclusions, les Parties entendent éviter tout malentendu quant à la répartition des responsabilités.</p>

<h2>6. Confidentialité</h2>
<p>Chacune des Parties traitera comme confidentielles toutes les informations reçues de l'autre partie dans le cadre du présent Contrat qui ne sont pas connues du public. Festilaw conservera la confidentialité de la documentation technique, des conceptions de produits, des formules, des données de vente et de toute autre information commerciale sensible du Client. Festilaw utilisera ces informations uniquement pour l'exécution de ses missions au titre du présent Contrat ou pour le respect d'obligations légales (par exemple leur communication à une autorité si la loi l'exige). Festilaw ne divulguera les informations confidentielles du Client à aucun tiers (à l'exception des autorités ou des sous-traitants tenus à la confidentialité, le cas échéant) sans le consentement écrit préalable du Client. De même, le Client conservera la confidentialité de toute information non publique relative à l'activité ou à la tarification de Festilaw. La présente clause de confidentialité demeure en vigueur même après la résiliation du Contrat.</p>
<p>(Remarque : conformément à la Section 2.2.6 des Conditions Générales et à l'article 3.1(e) du Contrat principal, Festilaw conserve la documentation technique et les dossiers de conformité pendant dix (10) ans suivant la résiliation ou l'expiration du Contrat, ainsi que l'exigent ses obligations en tant que Personne Responsable dans l'UE. La documentation sera détruite de manière sécurisée à l'issue de cette période, à moins que sa conservation ne soit requise par la loi ou par une procédure réglementaire ou judiciaire en cours. Une telle documentation ne sera ni restituée ni détruite à la demande du Client une fois la finalité de son utilisation atteinte, étant entendu que Festilaw peut en conserver des copies si la loi l'exige ou pour établir sa diligence en tant que Personne Responsable.)</p>

<h2>7. Durée et résiliation</h2>
<p><strong>7.1</strong>&nbsp;&nbsp;Durée initiale : la durée initiale du présent Contrat est d'un (1) an à compter de la date d'entrée en vigueur. Par la suite, le Contrat sera automatiquement reconduit pour des périodes successives d'un an aux mêmes conditions, sauf résiliation conformément à la Section 7.2. Les honoraires annuels de chaque période de renouvellement seront ceux prévus à la Section 3 (sous réserve de tout préavis d'ajustement donné).</p>
<p><strong>7.2</strong>&nbsp;&nbsp;Préavis de résiliation : chacune des Parties peut choisir de ne pas reconduire le Contrat à l'issue de la période en cours en adressant un préavis écrit d'au moins 60 jours avant la date de renouvellement. Si aucune partie ne donne de préavis en temps utile, le Contrat sera reconduit et les deux parties seront tenues pour la nouvelle période. Le préavis de résiliation/non-renouvellement doit être donné par écrit (le courriel est admis, sous réserve de confirmation de sa réception).</p>
<p><strong>7.3</strong>&nbsp;&nbsp;Résiliation pour faute : chacune des Parties peut résilier le présent Contrat avec effet immédiat avant le terme d'une période si l'autre partie commet une violation substantielle qui est soit insusceptible de réparation, soit n'est pas remédiée dans un délai de 14 jours à compter d'une mise en demeure écrite. Sont considérés comme des violations substantielles du Client : le défaut de paiement des honoraires à l'échéance (sous réserve d'un délai de régularisation de 14 jours), le manquement répété à fournir les informations ou la coopération requises au titre de la Section 4.2, la vente de produits en violation du droit de l'UE en matière de sécurité (mettant Festilaw en péril sur le plan juridique), ou la communication de fausses informations à Festilaw. Constituent des violations substantielles de Festilaw : un refus délibéré d'exécuter ses missions ou une série d'actes de négligence grave dans l'exercice des obligations de Personne Responsable. En outre, si le Client fait l'objet d'une procédure de faillite ou cesse son activité, Festilaw peut résilier (et réciproquement, si Festilaw ne peut plus légalement exercer ou fournir le service, elle peut résilier). La résiliation pour faute doit être formulée par écrit avec mention de la violation concernée.</p>
<p><strong>7.4</strong>&nbsp;&nbsp;Effet de la résiliation : à la résiliation ou au non-renouvellement, la désignation de Festilaw en tant que Personne Responsable prend fin à la date effective de résiliation. Le Client doit immédiatement cesser d'utiliser le nom/l'adresse de Festilaw sur tout nouvel étiquetage de produit, site internet ou support. (Le Client devrait prévoir de disposer d'une nouvelle Personne Responsable, ainsi que l'exige le droit de l'UE, à la date de résiliation, afin d'éviter toute interruption des ventes. Festilaw coopérera de bonne foi au transfert des responsabilités.) Festilaw conservera une copie des dossiers nécessaires au respect des obligations légales ou de conservation. Toute facture ou tout honoraire impayé au titre de services rendus avant la résiliation demeure exigible. Les Sections 5 (Responsabilité et garantie), 6 (Confidentialité), ainsi que toute autre clause qui, par sa nature, doit survivre, survivront à la résiliation.</p>

<h2>8. Dispositions diverses</h2>
<p><strong>8.1</strong>&nbsp;&nbsp;Droit applicable et juridiction : le présent Contrat est régi et interprété conformément au droit des Pays-Bas. Tout litige découlant du présent Contrat ou en lien avec celui-ci qui ne pourrait être résolu à l'amiable sera soumis à la compétence exclusive du tribunal compétent d'Oost-Brabant, siège de 's-Hertogenbosch, Pays-Bas.</p>
<p><strong>8.2</strong>&nbsp;&nbsp;Intégralité de l'accord : le présent Contrat constitue l'intégralité de l'accord entre Festilaw et le Client concernant le service de Personne Responsable. Il remplace toutes les discussions, propositions ou accords antérieurs (oraux ou écrits) sur ce sujet. Toute modification du présent Contrat doit être faite par écrit et signée par les deux Parties. Dans le cas où un bon de commande ou tout autre document du Client contiendrait des conditions, les conditions du présent Contrat prévaudront en cas de conflit.</p>
<p><strong>8.3</strong>&nbsp;&nbsp;Incessibilité : le Client ne peut céder ni transférer le présent Contrat (ni aucun droit/obligation qui en découle) à un tiers sans le consentement écrit préalable de Festilaw, sauf à une entité qui lui succède en cas de fusion ou d'acquisition de l'activité du Client (et moyennant notification à Festilaw). Festilaw ne peut céder le présent Contrat sans le consentement du Client, si ce n'est que Festilaw peut sous-traiter certaines tâches administratives à ses bureaux affiliés ou à des sous-traitants qualifiés en matière de conformité, à condition que Festilaw demeure entièrement responsable de l'exécution du Contrat.</p>
<p><strong>8.4</strong>&nbsp;&nbsp;Absence de partenariat/mandat : les Parties sont des contractants indépendants. Aucune disposition du présent Contrat ne crée de coentreprise, de partenariat ou de relation d'emploi entre Festilaw et le Client. Le Client est le fabricant/vendeur, et Festilaw est un prestataire de services. Sauf disposition expresse du présent Contrat aux fins de la représentation réglementaire, aucune des parties n'est le mandataire de l'autre, et aucune ne peut engager l'autre à l'égard d'une obligation envers un tiers.</p>
<p><strong>8.5</strong>&nbsp;&nbsp;Divisibilité : si une disposition du présent Contrat est jugée invalide ou inapplicable par un tribunal ou une autorité compétente, cette disposition sera retranchée et le reste du Contrat demeurera pleinement en vigueur. Les Parties négocieront de bonne foi le remplacement de toute disposition invalide par une disposition valide reflétant au plus près l'intention initiale et l'effet économique.</p>
<p><strong>8.6</strong>&nbsp;&nbsp;Renonciation : le fait pour l'une ou l'autre des Parties de ne pas faire appliquer une disposition ou de ne pas exercer un droit au titre du présent Contrat ne constitue pas une renonciation à cette disposition ou à ce droit. Toute renonciation doit être expresse et écrite pour être valable et ne s'appliquera à aucune autre circonstance que celle pour laquelle elle est consentie.</p>
<p><strong>8.7</strong>&nbsp;&nbsp;Langue : le présent Contrat est fourni au Client en anglais et, par commodité, dans la langue choisie par le Client. Toutes les notifications, la documentation et les communications au titre du présent Contrat peuvent être faites en anglais. En cas de divergence entre les versions linguistiques, la version anglaise prévaut.</p>
<p><strong>8.8</strong>&nbsp;&nbsp;Exemplaires et signatures électroniques : le Contrat peut être signé en deux exemplaires, qui constitueront ensemble un seul et même acte. Les signatures transmises par PDF joint à un courriel ou via une plateforme de signature électronique seront valables au même titre que des signatures originales.</p>
