<div class="annex-eyebrow">Anexo al Contrato de servicio de Persona Responsable</div>
<h1 style="font-size: 16px;">Condiciones Generales</h1>

<h2>1. Partes</h2>
<p><strong>Prestador del servicio:</strong> Festilaw B.V., sociedad constituida conforme al Derecho neerlandés, que actúa como «Persona Responsable» en el sentido de la normativa de la UE en materia de seguridad de los productos.</p>
<p><strong>Cliente:</strong> en lo sucesivo, el «Cliente» o la «Empresa».</p>
<p>Denominadas conjuntamente las «Partes».</p>

<h2>2. Designación y alcance de los servicios</h2>
<p><strong>2.1</strong>&nbsp;&nbsp;Designación de la Persona Responsable: el Cliente designa a Festilaw como su Persona Responsable en la Unión Europea para los productos de consumo vendidos en la UE, conforme a lo exigido por el Reglamento general de seguridad de los productos de la UE (UE) 2023/988 (GPSR). Festilaw acepta esta designación. El presente Contrato constituye el mandato escrito en virtud del cual Festilaw actúa como representante autorizado del Cliente en la UE, de conformidad con el artículo 4 del Reglamento (UE) 2019/1020 (para los productos armonizados) y con el GPSR para los productos de consumo no armonizados.</p>
<p><strong>2.2</strong>&nbsp;&nbsp;Alcance de los servicios: Festilaw desempeñará las siguientes funciones como Persona Responsable, según lo dispuesto por el Derecho de la UE:</p>
<p><strong>2.2.1</strong>&nbsp;&nbsp;Garantía de conformidad del producto: verificar que cada producto del Cliente, o determinados productos, destinados a los consumidores de la UE cumplen los requisitos de seguridad aplicables de la UE con arreglo al GPSR. Ello implica una supervisión general de que los productos han sido sometidos a las evaluaciones de riesgos exigidas y cumplen las normas de seguridad pertinentes. (Nota: Festilaw no ensayará los productos de forma independiente ni certificará su conformidad, sino que se basará en la documentación y las garantías facilitadas por el Cliente.)</p>
<p><strong>2.2.2</strong>&nbsp;&nbsp;Datos de contacto en la UE: facilitar una dirección de contacto en la UE (física) y una dirección electrónica (por ejemplo, correo electrónico) para las consultas de consumidores y autoridades, conforme a lo exigido por el Derecho de la UE. El nombre y la dirección en la UE de Festilaw figurarán en las etiquetas, el embalaje o la documentación adjunta de los productos del Cliente, así como en el sitio web del Cliente en la medida necesaria, para cumplir el requisito legal de que una Persona Responsable establecida en la UE sea identificable por los consumidores y los reguladores. Festilaw notificará sin demora al cliente cualquier cambio en estos datos de contacto.</p>
<p><strong>2.2.3</strong>&nbsp;&nbsp;Enlace con las autoridades y vigilancia del mercado: actuar como punto de contacto para las autoridades de vigilancia del mercado de la UE, incluida la respuesta a las consultas de los reguladores y la facilitación de la comunicación. Festilaw cooperará con las autoridades durante las investigaciones o los controles de seguridad facilitando la información y la documentación exigidas. Si una autoridad de la UE solicita información adicional sobre un producto o cuestiona un producto, Festilaw informará al Cliente y coordinará una respuesta oportuna. El Cliente debe apoyar a Festilaw en estas cuestiones (véase la sección 4.2 sobre los plazos de respuesta).</p>
<p><strong>2.2.4</strong>&nbsp;&nbsp;Asistencia en incidentes y retiradas: asistir en incidentes de seguridad de los productos, retiradas y notificaciones. Si se determina que un producto del Cliente presenta riesgos o se considera peligroso, Festilaw asesorará sobre las medidas de conformidad y asistirá en la notificación a las autoridades a través del sistema Safety Gate de la UE (Safety Business Gateway). Festilaw notificará a las autoridades sin demora indebida cualquier riesgo grave, según lo exigido por la ley. En tales casos, Festilaw ayudará asimismo a preparar los avisos públicos de retirada o los planes de acción correctiva exigidos, en cooperación con el cliente. El Cliente sigue siendo responsable de ejecutar las retiradas (por ejemplo, retirar o reparar los productos), pero deberá hacerlo con la orientación de Festilaw y de conformidad con las órdenes de las autoridades (véase la sección 4.3).</p>
<p><strong>2.2.5</strong>&nbsp;&nbsp;Revisión de etiquetas y embalaje (limitada): Festilaw verificará que las etiquetas y el embalaje de los productos del Cliente incluyen la información legalmente exigida (por ejemplo, los datos de contacto de Festilaw como Persona Responsable, el nombre y la dirección del fabricante, los identificadores del producto y cualquier advertencia exigida). Importante: el servicio estándar de Festilaw no incluye una revisión reglamentaria completa de todo el contenido de las etiquetas ni de las alegaciones publicitarias. Garantizar que las etiquetas, las instrucciones de uso y el embalaje cumplen toda la normativa de etiquetado aplicable de la UE (más allá de la presencia de los datos de la Persona Responsable) es responsabilidad del Cliente, salvo que el Cliente contrate por separado a Festilaw o a otro experto para tales servicios. (Esta exclusión se detalla con mayor amplitud en la sección 5.4.)</p>
<p><strong>2.2.6</strong>&nbsp;&nbsp;Comprobación anual de acceso: Festilaw celebrará una reunión o revisión anual con el Cliente para evaluar los datos pertinentes del producto. Durante esta revisión, Festilaw y el Cliente examinarán las ventas en la UE y seleccionarán de uno (1) a cinco (5) productos de muestra para confirmar que la documentación técnica exigida está fácilmente disponible y actualizada. Cuando sea necesario para cumplir sus obligaciones como Persona Responsable en la UE y para demostrar la diligencia debida ante las autoridades de vigilancia del mercado, Festilaw podrá conservar una copia de la documentación técnica del Cliente durante un máximo de diez (10) años a partir de la resolución o expiración del presente Contrato, de conformidad con la normativa de la UE aplicable en materia de seguridad de los productos. Festilaw garantizará medidas técnicas y organizativas adecuadas para proteger la confidencialidad, la integridad y la seguridad de la documentación conservada.</p>
<p><strong>2.2.7</strong>&nbsp;&nbsp;Verificación de las comunicaciones: Festilaw verificará que el correo electrónico de atención al cliente designado y los mecanismos de contacto del Cliente (en especial, el correo electrónico impreso en el embalaje o facilitado en el sitio web del Cliente para los consumidores de la UE) funcionan y están supervisados. De este modo se garantiza que, si las autoridades de la UE o los consumidores envían consultas relacionadas con la seguridad o comunicaciones urgentes (por ejemplo, en caso de retirada de un producto), estas lleguen al contacto apropiado. Festilaw comprobará estos puntos de contacto una vez al año y confirmará al Cliente que funcionan correctamente para una comunicación rápida.</p>
<p><strong>2.2.8</strong>&nbsp;&nbsp;Gestión de las consultas de consumidores ordinarios. Los datos de contacto en la UE de Festilaw se mostrarán en el embalaje y en línea; cualquier consulta de consumidores recibida a través de estos canales será registrada y remitida sin demora por Festilaw, y el Cliente garantizará respuestas exactas y oportunas de conformidad con el Derecho de la UE en materia de consumo (Festilaw no gestiona una línea de atención al consumidor más allá de esta función de reenvío). Hasta 2 horas anuales de esta asistencia son gratuitas.</p>

<h2>3. Honorarios, pago y servicios adicionales</h2>
<p><strong>3.1</strong>&nbsp;&nbsp;Honorario anual: el Cliente abonará un honorario anual por los servicios de Persona Responsable. Este honorario es exigible y pagadero dentro de los 30 días siguientes a la factura. El año de servicio comprende siempre del 1 de enero al 31 de diciembre. Si el Cliente inicia el servicio durante el año natural y no el 1 de enero, la primera factura será a prorrata y cubrirá únicamente los meses restantes de ese año natural hasta el 31 de diciembre (por ejemplo, a un Cliente que comience en julio se le facturarán seis (6) meses). Festilaw emitirá a continuación una nueva factura por el honorario anual íntegro en el mes de enero de cada año siguiente. El honorario cubre todos los elementos esenciales de la función de Persona Responsable descritos en el presente Contrato, incluidos:</p>
<p>La provisión de la dirección física y la dirección electrónica en la UE de Festilaw para el etiquetado de los productos y su indicación en el sitio web (a fin de cumplir el requisito de la UE de facilitar un contacto en la UE): ello incluye la autorización para que el Cliente imprima el nombre y los datos de contacto de Festilaw en el embalaje, los prospectos de los productos y el sitio web del Cliente dirigido a la UE.</p>
<p>La reunión anual de acceso y la comprobación de la documentación (sección 2.2) y un breve informe de dicha comprobación. El breve informe solo se facilita a las empresas con un catálogo de productos que supere los 100 SKUs.</p>
<p>La inclusión del nombre y la dirección de Festilaw en el sitio web y los materiales del Cliente, en la medida necesaria para el cumplimiento reglamentario en la UE (Festilaw facilitará la redacción o los archivos si fuera necesario, por ejemplo, un certificado de «Persona Responsable en la UE» o información para el sitio).</p>
<p>La verificación de la configuración de contacto (sección 2.2, Verificación de las comunicaciones) para garantizar que las comunicaciones de retirada llegarían a la persona adecuada.</p>
<p>Hasta 2 horas de asistencia o gestión básica de consultas de consumidores ordinarios según se describe anteriormente [servicio 2.2.8].</p>
<p>Festilaw confirma que no almacenará ni conservará los datos confidenciales de los productos del Cliente más allá de lo necesario para los servicios anteriores. Festilaw conservará copias de toda la documentación técnica y de los registros de conformidad relativos a los productos del Cliente durante un período de diez (10) años a partir de la resolución o expiración del presente Contrato, de conformidad con la normativa de la UE aplicable en materia de seguridad de los productos y con sus obligaciones como Persona Responsable en la UE.</p>
<p><strong>3.2</strong>&nbsp;&nbsp;Honorarios por tarifa horaria: si el Cliente requiere o solicita asistencia que exceda el alcance del servicio anual (por ejemplo, la gestión de una retirada de producto compleja, una correspondencia extensa con las autoridades o consultas de conformidad adicionales que superen las 2 horas incluidas), tales servicios adicionales se facturarán conforme a las siguientes tarifas horarias:</p>
<p>Asistencia sénior: EUR €145 por hora [tabla 3.1] (por ejemplo, para que los expertos sénior de conformidad de Festilaw interactúen con funcionarios públicos, gestionen comunicaciones de alto nivel con las autoridades o dirijan la respuesta a un incidente grave).</p>
<p>Asistencia júnior: EUR €100 por hora [tabla 3.1] (por ejemplo, para tareas más rutinarias como la redacción de respuestas a consultas de consumidores, la investigación básica sobre normativa u otras actividades de asistencia de nivel júnior).</p>
<p>Festilaw obtendrá la confirmación del Cliente antes de realizar cualquier trabajo adicional facturable. Se facturará al Cliente la asistencia adicional al final del mes en que se haya prestado (o una vez concluida una tarea concreta de asistencia en un incidente), con registros detallados del tiempo. El pago será exigible dentro de los 30 días siguientes a la factura.</p>
<p><strong>3.3</strong>&nbsp;&nbsp;Ajustes de precios: el honorario anual y las tarifas horarias podrán ser ajustados por Festilaw cada año el 1 de enero. El Cliente recibirá notificación por escrito 30 días antes de cualquier cambio de precio para un período de renovación. Si el Cliente se opone al precio ajustado, podrá resolver el Contrato al final del período vigente mediante notificación por escrito (conforme a la sección 7.2); en su defecto, los nuevos precios se aplicarán al siguiente período de renovación.</p>
<p><strong>3.4</strong>&nbsp;&nbsp;Tabla de servicio y pago</p>
<p>A continuación se detalla la especificación de los Servicios. Festilaw no asume responsabilidad alguna por actividades no incluidas expresamente en los Servicios adquiridos por el Cliente y pagadas como parte de estos. Queda a la entera discreción del Cliente qué servicios adicionales contrata. Cualquier incumplimiento del Derecho de la UE relativo a los productos o las operaciones del Cliente permanece enteramente por cuenta y responsabilidad del Cliente.</p>
<table class="terms">
    <thead>
        <tr><th style="width: 22%;">Servicio</th><th>Honorarios, pago</th></tr>
    </thead>
    <tbody>
        <tr><td>2.2.1</td><td>Asistencia sénior por tarifa horaria previa solicitud.</td></tr>
        <tr><td>2.2.2</td><td>Honorario anual</td></tr>
        <tr><td>2.2.3</td><td>Asistencia sénior por tarifa horaria previa solicitud.</td></tr>
        <tr><td>2.2.4</td><td>Asistencia sénior por tarifa horaria previa solicitud.</td></tr>
        <tr><td>2.2.5</td><td>Asistencia sénior por tarifa horaria previa solicitud.</td></tr>
        <tr><td>2.2.6</td><td>Honorario anual</td></tr>
        <tr><td>2.2.7</td><td>Honorario anual</td></tr>
        <tr><td>2.2.8</td><td>Honorario júnior por tarifa horaria / 2 horas anuales forman parte del honorario anual.</td></tr>
    </tbody>
</table>

<h2>4. Obligaciones del Cliente (Responsabilidades del Cliente)</h2>
<p>El Cliente se compromete a cumplir las siguientes obligaciones, a fin de permitir que Festilaw desempeñe sus funciones de Persona Responsable de manera eficaz y conforme a la ley:</p>
<p><strong>4.1</strong>&nbsp;&nbsp;Cumplimiento del Derecho de la UE: el Cliente garantiza que sus productos y sus operaciones comerciales cumplen toda la legislación europea aplicable en materia de protección de los consumidores y la normativa de productos, incluidas, entre otras:</p>
<p>El Reglamento general de seguridad de los productos (UE) 2023/988, y cualesquiera directivas o reglamentos específicos de productos pertinentes para los productos del Cliente. El Cliente confirma que ha llevado a cabo las evaluaciones de riesgos de seguridad de los productos necesarias y que ha establecido la documentación técnica exigida para sus productos, según lo dispuesto por el Derecho de la UE.</p>
<p>La Directiva sobre los derechos de los consumidores 2011/83/UE y la legislación conexa en materia de protección de los consumidores, en la medida en que resulten aplicables (por ejemplo, si el Cliente vende directamente a consumidores de la UE a través del comercio electrónico, respetará los derechos de los consumidores, como la información precontractual clara y el plazo de desistimiento (período de reflexión) de 14 días para las compras en línea).</p>
<p>Toda otra normativa pertinente de la UE en materia de comercio electrónico y la legislación específica de productos. Ello incluye la normativa sobre sustancias químicas y materiales utilizados en los productos (el Cliente garantiza que no se utilizan intencionadamente en sus productos sustancias prohibidas por directivas o reglamentos de la UE, y que respeta las restricciones de la UE sobre sustancias peligrosas), así como el cumplimiento de las normas sobre publicidad leal, garantía y responsabilidad por los productos.</p>
<p>Acceso a la documentación técnica: disponer o tener acceso inmediato a la documentación técnica de cada producto (por ejemplo, informes de ensayos de seguridad, expedientes técnicos, Declaraciones de Conformidad) para verificar la conformidad. Festilaw debe poder facilitar esta documentación a las autoridades de los Estados miembros de la UE previa solicitud. El Cliente proporcionará a Festilaw expedientes técnicos completos y actualizados de todos los productos vendidos en la UE (véanse las obligaciones del Cliente en la sección 4).</p>
<p>Al firmar el presente Contrato, el Cliente confirma que conoce y cumplirá la legislación anterior y cualesquiera actualizaciones de esta. El Cliente facilitará a Festilaw, previa solicitud, pruebas de conformidad (tales como informes de ensayos, certificados o informes de revisión) para fundamentar estas garantías. Si el Cliente tiene conocimiento de cualquier incumplimiento o infracción relacionados con sus productos (por ejemplo, el descubrimiento de una sustancia química prohibida en un producto, o un peligro para la seguridad), informará inmediatamente a Festilaw y adoptará medidas correctivas. Si Festilaw tiene conocimiento de cualquier incumplimiento o infracción, ello puede implicar que Festilaw deba notificarlo a las autoridades a través del sistema Safety Gate de la UE.</p>
<p><strong>4.2</strong>&nbsp;&nbsp;Provisión de información y documentación: el Cliente facilitará a Festilaw toda la información y el apoyo necesarios para que Festilaw desempeñe su función:</p>
<p>Lista de productos y actualizaciones: una relación de todos los productos del Cliente vendidos o que se vayan a vender en la UE, incluidos los nombres de los productos/SKUs, las descripciones y cualesquiera números de modelo o identificadores. El Cliente entregará una lista inicial en el momento de la firma del presente Contrato. Con posterioridad, el Cliente deberá mantener informada a Festilaw (al menos trimestralmente) de cualquier cambio, por ejemplo, los nuevos productos introducidos en el mercado de la UE o los productos descatalogados. De este modo se garantiza que Festilaw conozca en todo momento de qué artículos es responsable.</p>
<p>Documentación técnica: para cada producto, el Cliente facilitará o pondrá a disposición la documentación técnica de conformidad (según se define en el Derecho de la UE). Esta suele incluir la documentación de seguridad o conformidad del producto (por ejemplo, informes de ensayos, expediente de conformidad de seguridad general del producto, cualquier Declaración de Conformidad CE aplicable, evaluación de riesgos, etc.). El Cliente podrá facilitar copias de estos archivos a Festilaw o garantizar que puedan consultarse con rapidez previa solicitud. Si el Cliente prefiere no compartir los expedientes técnicos completos por anticipado, deberá al menos certificar su existencia y facilitar un resumen de su contenido, y proporcionarlos de inmediato si Festilaw o una autoridad los solicitan.</p>
<p>Respuestas oportunas (Safety Gate y autoridades): el Cliente es responsable de cooperar oportunamente en cualquier consulta de conformidad o incidente. Si Festilaw notifica al Cliente una solicitud de información de una autoridad de la UE o la necesidad de notificar un incidente a través del Safety Business Gateway, el Cliente responderá y facilitará sin demora toda la información exigida. En concreto, el Cliente deberá cumplir cualquier plazo fijado por Festilaw que tenga en cuenta los plazos legales de respuesta menos cuatro (4) días hábiles. Este margen permite a Festilaw revisar y remitir la información dentro del plazo oficial. Por ejemplo, si el Derecho de la UE o una autoridad exige una respuesta o documentación en un plazo de 10 días hábiles, Festilaw pedirá al Cliente que entregue el material necesario en un plazo de 6 días hábiles; si el Cliente no lo hace, incurrirá en un incumplimiento del presente Contrato. En tal caso, el Cliente será responsable de una penalización de EUR €500 diarios, hasta un máximo de €15,000 por incidente, por cada día hábil transcurrido a partir de la fecha solicitada en que se demore la información, hasta que esta se facilite. Esta penalización refleja las consecuencias potencialmente graves de una demora en el cumplimiento (multas o interrupciones de la actividad) y tiene por objeto fomentar la urgencia. Festilaw podrá renunciar a la penalización o reducirla a su discreción si la demora no llega a causar un incumplimiento o si concurren circunstancias atenuantes, pero se reserva el derecho de exigirla.</p>
<p>Notificación de accidentes y peligros: el Cliente debe informar a Festilaw de inmediato (a más tardar en un plazo de 2 días naturales) si tiene conocimiento de un incidente grave, accidente o problema de seguridad relacionado con un producto en el mercado de la UE (por ejemplo, una lesión de un consumidor, una reclamación de seguridad que sugiera un defecto del producto, o cualquier hecho que dé lugar a la obligación de notificar a los reguladores). El Derecho de la UE exige a los fabricantes «notificar de inmediato» los productos peligrosos y, «sin demora indebida», cualquier accidente grave causado por un producto. Por consiguiente, el Cliente facilitará a Festilaw todos los detalles del incidente y los datos pertinentes lo antes posible, de modo que Festilaw pueda asistir en la notificación a las autoridades a través del Safety Business Gateway y en la adopción de las medidas apropiadas. La omisión deliberada o negligente del Cliente de notificar tales problemas a Festilaw se considerará un incumplimiento sustancial del presente Contrato.</p>
<p><strong>4.3</strong>&nbsp;&nbsp;Cooperación en retiradas y acciones correctivas: en caso de que se determine que cualquier producto del Cliente es inseguro o no conforme, ya sea por una autoridad competente o por determinación mutua de las Partes:</p>
<p>Ejecución de la retirada: el Cliente se compromete a cooperar y ejecutar sin demora cualesquiera medidas correctivas o retiradas que sean necesarias para proteger a los consumidores, ya sean tales medidas impuestas por una autoridad o iniciadas voluntariamente. Si una autoridad de vigilancia del mercado de la UE ordena una retirada obligatoria o una orden de cese de venta de un producto, el Cliente cumplirá sin demora, según lo exigido por la ley. El Cliente se encargará de la logística de la retirada o recuperación de los productos del mercado, incluida la coordinación con distribuidores, minoristas y clientes según sea necesario. Festilaw asistirá facilitando orientación, comunicaciones oficiales a los reguladores y figurando como contacto para las autoridades en los avisos de retirada. Según el GPSR, una vez que los fabricantes tienen conocimiento de riesgos de seguridad, deben actuar sin demora (incluida la retirada o recuperación del producto) e informar a las autoridades a través del sistema Safety Gate. La cooperación diligente del Cliente es a la vez un requisito legal y una condición del presente contrato.</p>
<p>Comunicación pública y remedios: el Cliente redactará o finalizará los avisos de retirada dirigidos a los consumidores en cooperación con Festilaw (garantizando que cumplen las plantillas estándar y el contenido exigidos por la Comisión Europea o el Derecho nacional). Todo aviso de este tipo incluirá el contacto de Festilaw según se exija y será revisado por Festilaw antes de su publicación para garantizar la coherencia con la información facilitada a las autoridades. El Cliente ofrecerá los remedios apropiados a los consumidores (reparación, sustitución, reembolso, etc.) según lo exigido por el Derecho de la UE para los productos retirados. Los costes de la retirada (incluidos los reembolsos o reparaciones y cualesquiera avisos públicos) correrán a cargo del Cliente (salvo en la medida en que la retirada haya sido causada únicamente por la negligencia o el incumplimiento de Festilaw).</p>
<p>Acciones preventivas y de seguimiento: el Cliente investigará la causa raíz del problema de seguridad e implementará medidas para prevenir futuras incidencias. El Cliente mantendrá informada a Festilaw de las conclusiones de la investigación y de las medidas correctivas. Si las autoridades exigen informes de seguimiento (por ejemplo, el avance de la retirada, la destrucción de los artículos devueltos), el Cliente facilitará la información necesaria para que Festilaw la transmita. El Cliente se compromete asimismo a cooperar con cualesquiera acciones de retirada «forzosa» por parte de las autoridades, lo que significa que si, por ejemplo, una autoridad ordena directamente determinadas acciones (como advertencias públicas, incautaciones de productos, etc.), el Cliente no las obstaculizará y apoyará activamente dichas medidas.</p>
<p><strong>4.4</strong>&nbsp;&nbsp;Responsabilidades y reconocimientos adicionales:</p>
<p>Ausencia de sustancias ilegales: el Cliente garantiza que sus productos no contienen ninguna sustancia prohibida por la normativa de la UE en materia de sustancias químicas o de seguridad. Por ejemplo, el Cliente confirma que no utiliza materiales que infrinjan el Reglamento REACH de la UE u otras directivas que limiten las sustancias en los bienes de consumo. Esta garantía es fundamental dada la normativa de la UE sobre seguridad química en los productos de consumo (tales como las prohibiciones de determinados ftalatos, metales pesados u otras sustancias químicas tóxicas en los bienes de consumo). Si algún componente de un producto está regulado (por ejemplo, restricciones sobre pilas, etc.), el Cliente confirma el cumplimiento también de esas normas específicas.</p>
<p>Cumplimiento del Derecho de consumo: si el Cliente vende directamente a consumidores en la UE (a través de un sitio web u otras ventas directas), confirma que opera conforme a la legislación de la UE en materia de protección de los consumidores. Ello incluye facilitar información clara sobre los productos, respetar los derechos de los consumidores como las devoluciones y los reembolsos, y no incurrir en prácticas desleales o engañosas. El Cliente reconoce que el incumplimiento de la legislación en materia de protección de los consumidores puede acarrear sanciones o daños reputacionales, y afirma que dispone de sistemas para mantener la conformidad.</p>
<p>Actualizaciones sobre cambios normativos: el Cliente es responsable de mantenerse informado de cualquier cambio en la normativa de la UE específica de sus productos (proporcionando Festilaw una orientación razonable si tiene conocimiento de cambios, en especial los que afecten a la función de Persona Responsable). Si una nueva ley o norma de la UE impone requisitos adicionales a los productos (por ejemplo, un nuevo etiquetado, la prohibición de una determinada sustancia, un nuevo requisito de documentación, etc.), el Cliente adoptará las medidas necesarias para cumplir e informará a Festilaw de cómo se logra la conformidad.</p>
<p>Contactos designados: el Cliente designará una persona de contacto principal (y un suplente) que servirá de enlace con Festilaw. Estas personas deberán estar facultadas para tomar decisiones u obtener rápidamente decisiones dentro de la organización del Cliente en caso de una cuestión urgente de conformidad. El Cliente garantizará que al menos un contacto esté localizable con poca antelación (en el plazo de un día hábil) para cualquier comunicación urgente de seguridad procedente de Festilaw.</p>

<h2>5. Limitaciones del servicio y de la responsabilidad</h2>
<p><strong>5.1</strong>&nbsp;&nbsp;Festilaw no es responsable de los defectos de los productos ni de los daños a los consumidores: la función de Festilaw es estrictamente la de representante de conformidad y punto de contacto en la UE. Las Partes convienen en que Festilaw no es el fabricante ni el importador de los productos y no asume la responsabilidad del fabricante por los productos. El Cliente conserva la plena responsabilidad por la seguridad y la conformidad de los productos. En consecuencia, Festilaw no será responsable de ningún daño a bienes o lesión personal (incluida la muerte) derivados de defectos o del uso de los productos del Cliente, salvo en la medida en que dicho daño sea causado directamente por la negligencia grave o el dolo de la propia Festilaw. Ello significa que, si los consumidores u otros terceros presentan reclamaciones relativas a los productos (por ejemplo, lesiones por el uso del producto), el Cliente asumirá toda la responsabilidad y los costes, y si se nombra o implica a Festilaw en razón de su función, el Cliente indemnizará a Festilaw (véase la sección 5.3). Las funciones de Festilaw se limitan a las de una Persona Responsable con arreglo al presente Contrato y a la ley aplicable; Festilaw no presta control de calidad general, supervisión de la fabricación ni seguro alguno frente a los riesgos de los productos.</p>
<p><strong>5.2</strong>&nbsp;&nbsp;Limitación de la responsabilidad de Festilaw: en la máxima medida permitida por la ley, si se declara a Festilaw responsable frente al Cliente por cualquier reclamación derivada del presente Contrato (ya sea contractual, extracontractual o de otro tipo), la responsabilidad agregada máxima de Festilaw se limitará a un importe no superior al del honorario anual abonado por el Cliente respecto del año contractual en curso (es decir, el honorario anual de {{ $fee }} €). En ningún caso será Festilaw responsable de daños indirectos, consecuenciales o punitivos, tales como el lucro cesante, la pérdida de ventas o el daño reputacional, aun cuando se le hubiera advertido de la posibilidad de tales daños. Las Partes reconocen que el honorario anual se establece en consideración a este límite de responsabilidad. Festilaw no es una aseguradora y no puede asumir un riesgo ilimitado por el honorario nominal del servicio. El Cliente acepta que debe mantener un seguro adecuado frente a la responsabilidad por los productos y otros riesgos según sea necesario.</p>
<p>Fundamento: la limitación anterior es una condición esencial del acuerdo de Festilaw de prestar los servicios. Ambas Partes convienen en que el resarcimiento potencial del Cliente por cualquier incumplimiento o error de Festilaw es limitado y razonable dada la naturaleza de los servicios. En cualquier caso, toda reclamación del Cliente contra Festilaw por incumplimiento o negligencia deberá interponerse dentro de los 90 días siguientes a que el Cliente tenga conocimiento del hecho que da origen a la reclamación, y a más tardar 1 año después del hecho. Si el Cliente no notifica a Festilaw una posible reclamación o problema dentro de los 90 días siguientes a su descubrimiento, renuncia a su derecho a reclamar sobre esa cuestión. (Este requisito de notificación en un plazo de 90 días garantiza una resolución oportuna y que Festilaw pueda intentar mitigar cualquier perjuicio.)</p>
<p><strong>5.3</strong>&nbsp;&nbsp;Indemnización: el Cliente se compromete a indemnizar y mantener indemne a Festilaw y a sus administradores, empleados y agentes frente a todas y cada una de las pérdidas, daños, responsabilidades, multas, penalizaciones, costes y gastos (incluidos los honorarios legales razonables) derivados de o relacionados con cualesquiera reclamaciones de terceros o acciones reguladoras que se refieran a los productos del Cliente o al incumplimiento por el Cliente de sus obligaciones. Esta indemnización cubre, por ejemplo: si una autoridad nacional impone una multa a Festilaw o emprende acciones legales debido a que un producto del Cliente es inseguro o no conforme (salvo que ello sea causado por el hecho de que Festilaw no haya remitido información que el Cliente hubiera facilitado), o si un consumidor demanda a Festilaw alegando una lesión causada por un producto. El Cliente asumirá la defensa y abonará cualesquiera importes resultantes. El Cliente indemnizará asimismo a Festilaw por cualquier perjuicio causado por el hecho de que el Cliente no facilite información exacta de forma oportuna (por ejemplo, si Festilaw incurre en penalizaciones por incumplir un plazo de notificación debido a que el Cliente demoró o retuvo la información). Festilaw notificará sin demora al Cliente cualquier reclamación o acción de la que tenga conocimiento, y permitirá que el Cliente la defienda (con la cooperación razonable de Festilaw). Esta cláusula subsiste tras la resolución del Contrato.</p>
<p><strong>5.4</strong>&nbsp;&nbsp;Servicios excluidos: las Partes reconocen que el servicio de Persona Responsable de Festilaw se centra en el apoyo al cumplimiento reglamentario y no incluye otros servicios de consultoría de producto o de negocio, salvo pacto en contrario por escrito. Salvo que se establezca un acuerdo por separado (o se utilicen horas adicionales conforme a la sección 3.2), Festilaw no es responsable de:</p>
<p>Ensayo o certificación de productos: Festilaw no ensayará los productos en cuanto a seguridad o conformidad, ni obtendrá certificados (como los certificados CE) por cuenta del Cliente. Estas siguen siendo obligaciones del Cliente (si bien Festilaw puede recomendar laboratorios u organismos de certificación si se le solicita).</p>
<p>Revisiones exhaustivas de etiquetas/embalaje: la comprobación de las etiquetas por parte de Festilaw se limita a garantizar la presencia de la información de contacto exigida y las marcas de seguridad evidentes. Festilaw no revisa el diseño gráfico, las alegaciones publicitarias ni las traducciones de las etiquetas en cuanto a su exactitud legal. El Cliente debería recurrir a expertos en conformidad para una revisión completa de las etiquetas si fuera necesario.</p>
<p>Cumplimiento legal ajeno a la seguridad de los productos de consumo de la UE: la función de Festilaw está vinculada al cumplimiento en materia de seguridad de los productos de consumo de la UE. Otros ámbitos jurídicos, por ejemplo, el cumplimiento en materia de protección de datos (RGPD), las cuestiones fiscales o de IVA, las obligaciones legales corporativas generales, etc., quedan fuera del alcance del presente Contrato.</p>
<p>Gestión de consultas o reclamaciones de consumidores: Festilaw no gestiona un centro de llamadas ni un servicio de atención al cliente para el Cliente. Si bien el contacto de Festilaw puede figurar en los productos por motivos reglamentarios, cualquier consulta de consumidores recibida por Festilaw se remitirá al Cliente. Es responsabilidad del Cliente responder a los consumidores (Festilaw puede asistir en la redacción de respuestas relativas a la seguridad, si se realiza dentro de las horas de asistencia incluidas o bien de forma facturable).</p>
<p>Derechos de importación/aduaneros: Festilaw no actúa como importador oficial. Garantizar que los productos superen los trámites aduaneros (más allá de facilitar la información exigida de la Persona Responsable) corresponde al Cliente o a sus proveedores logísticos. Si las autoridades aduaneras se ponen en contacto con Festilaw, Festilaw las remitirá al agente de importación del Cliente.</p>
<p>Si el Cliente desea cualquiera de los servicios anteriores por parte de Festilaw, las Partes deberán negociar un acuerdo o anexo por separado (con posibles honorarios adicionales). Al aclarar estas exclusiones, las Partes pretenden evitar malentendidos sobre el reparto de responsabilidades.</p>

<h2>6. Confidencialidad</h2>
<p>Ambas Partes tratarán como confidencial toda la información recibida de la otra parte en relación con el presente Contrato que no sea de dominio público. Festilaw mantendrá confidencial la documentación técnica, los diseños de productos, las fórmulas, los datos de ventas y cualquier otra información comercial sensible del Cliente. Festilaw utilizará dicha información exclusivamente para el desempeño de sus funciones en virtud del presente Contrato o para el cumplimiento de obligaciones legales (por ejemplo, para compartirla con una autoridad si legalmente se exige). Festilaw no revelará la información confidencial del Cliente a ningún tercero (salvo a las autoridades o a los subcontratistas sujetos a confidencialidad, si se recurre a alguno) sin el consentimiento previo por escrito del Cliente. Del mismo modo, el Cliente mantendrá confidencial cualquier información no pública sobre la actividad o los precios de Festilaw. Esta cláusula de confidencialidad permanece en vigor incluso tras la resolución del Contrato.</p>
<p>(Nota: de conformidad con la sección 2.2.6 de las Condiciones Generales y el artículo 3.1(e) del Contrato Principal, Festilaw conserva la documentación técnica y los registros de conformidad durante diez (10) años a partir de la resolución o expiración del Contrato, según lo exigido por sus obligaciones como Persona Responsable en la UE. La documentación se destruirá de forma segura al término de dicho período, salvo que la ley o procedimientos reguladores o legales en curso exijan su conservación. Dicha documentación no se devolverá ni destruirá a solicitud del Cliente una vez cumplida la finalidad de su uso, si bien Festilaw podrá conservar copias según lo exigido por la ley o para acreditar su diligencia debida como Persona Responsable.)</p>

<h2>7. Duración y resolución</h2>
<p><strong>7.1</strong>&nbsp;&nbsp;Duración inicial: la duración inicial del presente Contrato es de un (1) año a partir de la fecha de entrada en vigor. Con posterioridad, el Contrato se renovará automáticamente por períodos sucesivos de un año en las mismas condiciones, salvo que se resuelva conforme a la sección 7.2. El honorario anual de cada período de renovación será el establecido en la sección 3 (con sujeción a cualquier notificación de ajuste que se haya dado).</p>
<p><strong>7.2</strong>&nbsp;&nbsp;Preaviso de resolución: cualquiera de las Partes podrá optar por no renovar el Contrato al final del período vigente mediante preaviso por escrito de al menos 60 días antes de la fecha de renovación. Si ninguna de las partes da un preaviso oportuno, el Contrato se renovará y ambas partes quedarán obligadas por el nuevo período. El preaviso de resolución/no renovación deberá darse por escrito (se admite el correo electrónico, siempre que se confirme su recepción).</p>
<p><strong>7.3</strong>&nbsp;&nbsp;Resolución por causa justificada: cualquiera de las Partes podrá resolver el presente Contrato con efecto inmediato antes del final de un período si la otra parte comete un incumplimiento sustancial que sea insubsanable o que no se subsane en un plazo de 14 días a partir del preaviso por escrito. Se considerarán incumplimientos sustanciales del Cliente: el impago de los honorarios a su vencimiento (con sujeción a un plazo de subsanación de 14 días), la reiterada falta de provisión de la información o la cooperación exigidas conforme a la sección 4.2, la venta de productos infringiendo la legislación de seguridad de la UE (poniendo a Festilaw en peligro jurídico), o la comunicación de información falsa a Festilaw. Los incumplimientos sustanciales de Festilaw incluyen: una negativa deliberada a desempeñar sus funciones o una pauta de negligencia grave en el cumplimiento de las obligaciones de Persona Responsable. Adicionalmente, si el Cliente entra en concurso o cesa su actividad, Festilaw podrá resolver (y a la inversa, si Festilaw ya no puede operar legalmente o prestar el servicio, podrá resolver). La resolución por causa justificada deberá comunicarse por escrito con referencia al incumplimiento.</p>
<p><strong>7.4</strong>&nbsp;&nbsp;Efectos de la resolución: tras la resolución o la no renovación, la designación de Festilaw como Persona Responsable finaliza en la fecha efectiva de la resolución. El Cliente deberá cesar de inmediato el uso del nombre/dirección de Festilaw en cualesquiera nuevas etiquetas de productos, sitios web o materiales. (El Cliente debería prever contar con una nueva Persona Responsable, según lo exigido por el Derecho de la UE, para la fecha de resolución, a fin de evitar interrupciones en las ventas. Festilaw cooperará de buena fe en la transferencia de responsabilidades.) Festilaw conservará copia de los registros necesarios para el cumplimiento legal o la conservación de documentos. Cualesquiera facturas u honorarios pendientes por servicios prestados antes de la resolución seguirán siendo pagaderos. Las secciones 5 (Responsabilidad e indemnización), 6 (Confidencialidad) y cualesquiera otras cláusulas que por su naturaleza deban subsistir, subsistirán tras la resolución.</p>

<h2>8. Disposiciones diversas</h2>
<p><strong>8.1</strong>&nbsp;&nbsp;Ley aplicable y jurisdicción: el presente Contrato se regirá e interpretará de conformidad con las leyes de los Países Bajos. Cualquier controversia derivada de o relacionada con el presente Contrato que no pueda resolverse de forma amistosa se someterá a la jurisdicción exclusiva del tribunal competente de Oost-Brabant, sede de 's-Hertogenbosch, Países Bajos.</p>
<p><strong>8.2</strong>&nbsp;&nbsp;Acuerdo íntegro: el presente Contrato constituye el entendimiento íntegro entre Festilaw y el Cliente en relación con el servicio de Persona Responsable. Sustituye a todas las conversaciones, propuestas o acuerdos anteriores (ya sean orales o escritos) sobre esta materia. Toda modificación del presente Contrato deberá realizarse por escrito y ser firmada por ambas Partes. En caso de que cualquier orden de compra u otro documento del Cliente contenga condiciones, prevalecerán las condiciones del presente Contrato en la medida de cualquier conflicto.</p>
<p><strong>8.3</strong>&nbsp;&nbsp;Prohibición de cesión: el Cliente no podrá ceder ni transferir el presente Contrato (ni ningún derecho u obligación en virtud del mismo) a otra parte sin el consentimiento previo por escrito de Festilaw, salvo a una entidad sucesora en caso de fusión o adquisición de la actividad del Cliente (y con notificación a Festilaw). Festilaw no podrá ceder el presente Contrato sin el consentimiento del Cliente, salvo que Festilaw podrá subcontratar determinadas tareas administrativas a sus oficinas afiliadas o a subcontratistas de conformidad cualificados, siempre que Festilaw siga siendo plenamente responsable del cumplimiento del Contrato.</p>
<p><strong>8.4</strong>&nbsp;&nbsp;Ausencia de sociedad/agencia: las Partes son contratistas independientes. Nada en el presente Contrato crea una empresa conjunta, una sociedad o una relación laboral entre Festilaw y el Cliente. El Cliente es el fabricante/vendedor, y Festilaw es un prestador de servicios. Salvo lo expresamente establecido en el presente Contrato a efectos de la representación reglamentaria, ninguna de las partes es agente de la otra, y ninguna puede obligar a la otra frente a obligación alguna con terceros.</p>
<p><strong>8.5</strong>&nbsp;&nbsp;Divisibilidad: si un tribunal o autoridad de jurisdicción competente declara inválida o inaplicable cualquier disposición del presente Contrato, dicha disposición se separará y el resto del Contrato permanecerá en pleno vigor. Las Partes negociarán de buena fe para sustituir cualquier disposición inválida por una disposición válida que refleje del modo más aproximado la intención original y el efecto económico.</p>
<p><strong>8.6</strong>&nbsp;&nbsp;Renuncia: el hecho de que cualquiera de las Partes no exija el cumplimiento de una disposición o no ejerza un derecho en virtud del presente Contrato no constituirá una renuncia a esa disposición o derecho. Toda renuncia deberá ser explícita y constar por escrito para ser eficaz, y no se aplicará a circunstancias distintas de aquellas para las que se otorgue.</p>
<p><strong>8.7</strong>&nbsp;&nbsp;Idioma: el presente Contrato se facilita al Cliente en inglés y, por comodidad, en el idioma elegido por el Cliente. Todas las notificaciones, la documentación y las comunicaciones en virtud del presente Contrato podrán realizarse en inglés. En caso de cualquier discrepancia entre las versiones lingüísticas, prevalecerá la versión inglesa.</p>
<p><strong>8.8</strong>&nbsp;&nbsp;Ejemplares y firmas electrónicas: el Contrato podrá firmarse en dos ejemplares, que conjuntamente constituirán un único instrumento. Las firmas transmitidas por PDF a través de correo electrónico o mediante plataforma de firma electrónica serán válidas como firmas originales.</p>
