<div class="muted" style="text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px;">Attachment to the Responsible Person Service Agreement</div>
<h1 style="font-size: 16px;">General Terms</h1>

<h2>1. Parties</h2>
<p><strong>Service Provider:</strong> Festilaw B.V., a company incorporated under Dutch law, acting as the "Responsible Person" within the meaning of EU product safety regulations.</p>
<p><strong>Client:</strong> hereinafter "Client" or the "Company".</p>
<p>Together referred to as "Parties".</p>

<h2>2. Appointment and Scope of Services</h2>
<p><strong>2.1</strong>&nbsp;&nbsp;Responsible Person Appointment: Client appoints Festilaw as its European Union Responsible Person for consumer products sold in the EU, as required by the EU General Product Safety Regulation (EU) 2023/988 (GPSR). Festilaw accepts this appointment. This Agreement serves as the written mandate for Festilaw to act as Client's authorized representative in the EU, in accordance with Article 4 of Regulation (EU) 2019/1020 (for harmonized products) and the GPSR for non-harmonized consumer products.</p>
<p><strong>2.2</strong>&nbsp;&nbsp;Scope of Services: Festilaw shall perform the following duties as a Responsible Person as mandated by EU law:</p>
<p><strong>2.2.1</strong>&nbsp;&nbsp;Product Compliance Assurance: Verifying that each or specific Client product intended for EU consumers meets applicable EU safety requirements under the GPSR. This entails a general oversight that products have undergone required risk assessments and comply with relevant safety standards. (Note: Festilaw will not independently test products or certify compliance but will rely on documentation and assurances provided by Client.)</p>
<p><strong>2.2.2</strong>&nbsp;&nbsp;EU Contact Information: Providing a EU contact address (physical) and an electronic address (e.g. email) for consumer and authority inquiries, as required by EU law. Festilaw's name and EU address shall appear on Client's product labels, packaging, or accompanying documentation, and on Client's website as needed, to fulfill the legal requirement that an EU-based Responsible Person be identifiable to consumers and regulators. Festilaw will promptly notify client of any changes to this contact information.</p>
<p><strong>2.2.3</strong>&nbsp;&nbsp;Authority Liaison &amp; Market Surveillance: Acting as the point of contact for EU market surveillance authorities, including responding to inquiries from regulators and facilitating communication. Festilaw will cooperate with authorities during investigations or safety checks by providing required information and documentation. If an EU authority requests additional product information or takes issue with a product, Festilaw will inform Client and coordinate a timely response. Client must support Festilaw in these matters (see Section 4.2 on response timelines).</p>
<p><strong>2.2.4</strong>&nbsp;&nbsp;Incident and recall assistance: Assisting with product safety incidents, recalls, and notifications. If a Client product is found to pose risks or is deemed dangerous, Festilaw will advise on compliance steps and assist in notifying authorities via the EU Safety Gate system (Safety Business Gateway). Festilaw will notify authorities without undue delay of any serious risks, as required by law. In such cases, Festilaw will also help prepare any required public recall notices or corrective action plans in cooperation with client. Client remains responsible for executing recalls (e.g. withdrawing or repairing products) but must do so with Festilaw's guidance and in line with authority orders (see Section 4.3).</p>
<p><strong>2.2.5</strong>&nbsp;&nbsp;Label &amp; packaging review (Limited): Festilaw will verify that Client's product labels and packaging include the legally required information (e.g. Festilaw's contact details as Responsible Person, manufacturer name/address, product identifiers, any required warnings). Important: Festilaw's standard service does not include a full regulatory review of all label content or marketing claims. Ensuring that labels, user instructions, and packaging meet all applicable EU labeling regulations (beyond the presence of the Responsible Person's details) is the responsibility of Client, unless Client separately contracts Festilaw or another expert for such services. (This exclusion is further detailed in Section 5.4.)</p>
<p><strong>2.2.6</strong>&nbsp;&nbsp;Annual Access Check: Festilaw will conduct one annual meeting or review with the Client to assess to relevant product data. During this review, Festilaw and the Client shall examine EU sales and select one (1) to five (5) sample products to confirm that the required technical documentation is readily available and up to date. Where necessary to fulfil its obligations as EU Responsible Person and to demonstrate due diligence toward market surveillance authorities, Festilaw may retain a copy of the Client's technical documentation for up to ten (10) years following the termination or expiration of this Agreement, in accordance with applicable EU product safety regulations. Festilaw shall ensure appropriate technical and organizational measures to protect the confidentiality, integrity, and security of the retained documentation.</p>
<p><strong>2.2.7</strong>&nbsp;&nbsp;Communication Verification: Festilaw will verify that Client's designated customer service email and contact mechanisms (especially the email printed on packaging or provided on Client's website for EU consumers) are working and monitored. This ensures that if EU authorities or consumers send safety-related inquiries or urgent communications (e.g. in case of a product recall), they will reach the appropriate contact. Festilaw will test these contact points once per year and confirm to Client that they function correctly for rapid communication.</p>
<p><strong>2.2.8</strong>&nbsp;&nbsp;Handling questions of regular consumers. Festilaw's EU contact details shall be displayed on packaging and online; any consumer inquiries received via these channels will be promptly logged and forwarded by Festilaw, and Client shall ensure accurate, timely responses in accordance with EU consumer law (Festilaw does not operate a consumer helpline beyond this forwarding function). Up to 2 hours annually of this support is free of charge.</p>

<h2>3. Fees, Payment, and Additional Services</h2>
<p><strong>3.1</strong>&nbsp;&nbsp;Annual fee: Client shall pay an annual fee for the Responsible Person services. This fee is due and payable within 30 days of invoice. The service year always runs from 1 January to 31 December. If Client starts the service during the calendar year rather than on 1 January, the first invoice will be pro-rata, covering only the remaining months of that calendar year until 31 December (for example, a Client starting in July will be invoiced for six (6) months). Festilaw shall then issue a new invoice for the full annual fee in January of each following year. The fee covers all the essentials of the Responsible Person role as described in this Agreement, including:</p>
<p>Provision of Festilaw's EU physical address and electronic address for product labeling and website listing (to meet the EU requirement of providing an EU contact): this includes permission for Client to print Festilaw's name and contact details on packaging, product inserts, and Client's EU-facing website.</p>
<p>The annual access meeting &amp; documentation check (Section 2.2) and a brief report of that check. The brief report is only provided to companies with a product catalogue exceeding 100 SKUs.</p>
<p>Inclusion of Festilaw's name and address on Client's website and materials, as needed for EU regulatory compliance (Festilaw will provide wording or files if required, e.g. a "EU Responsible Person" certificate or info for the site).</p>
<p>Verification of contact setup (Section 2.2, Communication Verification) to ensure recall communications would reach the right person.</p>
<p>Up to 2 hours of support/basic handling questions of regular consumers as described above [service 2.2.8].</p>
<p>Festilaw confirms it will not store or keep Client's confidential product data beyond what is necessary for the above services. Festilaw shall retain copies of all technical documentation and compliance records relating to Client's products for a period of ten (10) years following the termination or expiry of this Agreement, in accordance with applicable EU product safety regulations and its obligations as EU Responsible Person.</p>
<p><strong>3.2</strong>&nbsp;&nbsp;Hourly Rate Fees: Should Client require or request assistance beyond the scope of the annual service (for example, handling a complex product recall, extensive correspondence with authorities, or extra compliance consultations beyond the included 2 hours), such additional services will be billed at the following hourly rates:</p>
<p>Senior Support: EUR €145 per hour [table 3.1] (e.g. for Festilaw's senior compliance experts to interact with government officials, manage high-level communications with authorities, or lead a serious incident response).</p>
<p>Junior Support: EUR €100 per hour [table 3.1] (e.g. for more routine tasks such as drafting responses to consumer questions, doing basic research on regulations, or other junior-level support activities).</p>
<p>Festilaw will obtain confirmation from Client before performing any billable additional work. Client will be invoiced for additional support at the end of the month in which it was provided (or upon completion of a specific incident support task), with detailed time logs. Payment is due within 30 days of invoice.</p>
<p><strong>3.3</strong>&nbsp;&nbsp;Price Adjustments: The annual fee and hourly rates may be adjusted by Festilaw each year on the 1st of January. Client will receive written notice 30 days before any price change for a renewal term. If Client objects to the adjusted price, it may terminate the Agreement at the end of the then-current term by providing written notice (per Section 7.2), failing which the new prices will apply for the next renewal term.</p>
<p><strong>3.4</strong>&nbsp;&nbsp;Table of Service and Payment</p>
<p>Below is the specification of the Services. Festilaw assumes no responsibility for any activities not expressly included in, and paid for as part of, the Services purchased by Client. It is solely at Client's discretion which additional services it engages. Any non-compliance with EU law relating to Client's products or operations remains entirely at Client's risk and responsibility.</p>
<table class="terms">
    <thead>
        <tr><th style="width: 22%;">Service</th><th>Fees, Payment</th></tr>
    </thead>
    <tbody>
        <tr><td>2.2.1</td><td>Senior support by hourly rate upon request.</td></tr>
        <tr><td>2.2.2</td><td>Annual fee</td></tr>
        <tr><td>2.2.3</td><td>Senior support by hourly rate upon request.</td></tr>
        <tr><td>2.2.4</td><td>Senior support by hourly rate upon request.</td></tr>
        <tr><td>2.2.5</td><td>Senior support by hourly rate upon request.</td></tr>
        <tr><td>2.2.6</td><td>Annual fee</td></tr>
        <tr><td>2.2.7</td><td>Annual fee</td></tr>
        <tr><td>2.2.8</td><td>Junior fee by hourly rate / 2 hours annually is part of the annual fee.</td></tr>
    </tbody>
</table>

<h2>4. Obligations of Client (Client Responsibilities)</h2>
<p>Client agrees to fulfil the following obligations, to enable Festilaw to carry out its Responsible Person duties effectively and in compliance with the law:</p>
<p><strong>4.1</strong>&nbsp;&nbsp;Compliance with EU Laws: Client warrants that its products and business operations comply with all applicable European consumer protection laws and product regulations, including but not limited to:</p>
<p>The General Product Safety Regulation (EU) 2023/988, and any specific product directives or regulations relevant to Client's products. Client confirms that it has conducted the necessary product safety risk assessments and has established the required technical documentation for its products, as mandated by EU law.</p>
<p>The EU Consumer Rights Directive 2011/83/EU and related consumer protection laws, to the extent applicable (for example, if Client sells directly to EU consumers via e-commerce, it will honor consumer rights such as clear pre-contract information and the 14-day withdrawal (cooling-off) period for online purchases).</p>
<p>All other relevant EU e-commerce regulations and product-specific legislation. This includes regulations on chemicals and materials used in products (Client guarantees that no substances banned by EU directives or regulations are intentionally used in its products, and that it abides by EU restrictions on hazardous substances), as well as adherence to fair advertising, warranty, and product liability rules.</p>
<p>Technical documentation access: Holding or having immediate access to the technical documentation for each product (e.g. safety test reports, technical files, Declarations of Conformity) to verify compliance. Festilaw must be able to furnish this documentation to EU Member State authorities upon request. Client shall supply Festilaw with complete and up-to-date technical files for all EU-sold products (see Client's obligations in Section 4).</p>
<p>By signing this Agreement, Client confirms it is aware of and will follow the above laws and any updates thereto. Client will furnish Festilaw, upon request, with evidence of compliance (such as test reports, certificates, or review reports) to substantiate these warranties. If Client becomes aware of any non-compliance or violation related to its products (e.g. discovery of a banned chemical in a product, or a safety hazard), it shall immediately inform Festilaw and take remedial actions. If Festilaw becomes aware of any non-compliance or violation this can mean Festilaw needs to notifying authorities via the EU Safety Gate system.</p>
<p><strong>4.2</strong>&nbsp;&nbsp;Provision of Information &amp; Documentation: Client shall provide Festilaw with all information and support needed for Festilaw to fulfill its role:</p>
<p>Product List &amp; Updates: An overview of all Client products sold or to be sold in the EU, including product names/SKUs, descriptions, and any model numbers or identifiers. Client will deliver an initial list upon signing this Agreement. Thereafter, Client must keep Festilaw updated (on at least a quarterly basis) with any changes, for example, new products introduced to the EU market, or products discontinued. This ensures Festilaw always knows which articles it is responsible for.</p>
<p>Technical Documentation: For each product, Client will provide or make available the technical compliance documentation (as defined in EU law). This typically includes the product's safety or conformity documentation (e.g. test reports, General Product Safety compliance file, any applicable CE Declaration of Conformity, risk assessment, etc.). Client can either provide copies of these files to Festilaw or ensure that they can be accessed swiftly upon request. If Client prefers not to share full technical files in advance, it must at least certify their existence and provide a summary of contents, and immediately supply them if Festilaw or an authority requests them.</p>
<p>Timely Responses (Safety Gate &amp; Authorities): Client is responsible for timely cooperation in any compliance inquiry or incident. If Festilaw notifies Client of an information request from an EU authority or a need to report an incident via the Safety Business Gateway, Client shall respond and provide all required information promptly. Specifically, Client must meet any deadline given by Festilaw that factors in the legal response times minus four (4) working days. This buffer allows Festilaw to review and forward information within the official timeframe. For example, if EU law or an authority requires a reply or documentation within 10 working days, Festilaw will ask Client to deliver the necessary materials within 6 working days, if Client fails to do so, it will be in breach of this Agreement. In such case, Client will be liable for a penalty of EUR €500 per day, up to a maximum of €15,000 per incident for each working day past the requested date that the information is delayed, until the information is provided. This penalty reflects the potentially severe consequences of delayed compliance (fines or business disruptions) and is meant to encourage urgency. Festilaw may waive or reduce the penalty at its discretion if the delay does not ultimately cause non-compliance or if there are extenuating circumstances but reserves the right to enforce it.</p>
<p>Accident and Hazard Reporting: Client must inform Festilaw immediately (within 2 calendar days at most) if it becomes aware of a serious incident, accident, or safety issue involving a product in the EU market (for example, a consumer injury, a safety complaint suggesting a product defect, or any event that would trigger an obligation to notify regulators). EU law requires manufacturers to "immediately notify" dangerous products and, "without undue delay," any serious accidents caused by a product. Therefore, Client shall provide Festilaw with all details of the incident and relevant data as soon as possible, so that Festilaw can assist in notifying authorities via the Safety Business Gateway and taking appropriate action. Deliberate or negligent failure by Client to report such issues to Festilaw will be considered a material breach of this Agreement.</p>
<p><strong>4.3</strong>&nbsp;&nbsp;Cooperation in Recalls and Corrective Actions: In the event any Client product is deemed unsafe or non-compliant by a competent authority or by mutual determination of the Parties:</p>
<p>Recall Execution: Client agrees to promptly cooperate with and execute any corrective measures or recalls that are necessary to protect consumers, whether such measures are mandated by an authority or initiated voluntarily. If an EU market surveillance authority issues a mandatory recall or stop-sale order for a product, Client will comply without delay, as required by law. Client will handle the logistics of withdrawing or recalling products from the market, including coordination with distributors, retailers, and customers as needed. Festilaw will assist by providing guidance, official communications to regulators, and by being listed as the contact for authorities on recall notices. According to the GPSR, once manufacturers become aware of safety risks, they must act promptly (including product withdrawal or recall) and inform authorities via the Safety Gate system. Client's swift cooperation is both a legal requirement and a term of this contract.</p>
<p>Public Communication and Remedies: Client will draft or finalize consumer-facing recall notices in cooperation with Festilaw (ensuring they meet the standard templates and content required by the European Commission or national law). Any such notice will include Festilaw's contact as required and be reviewed by Festilaw before publication to ensure consistency with information provided to authorities. Client will offer the appropriate remedies to consumers (repair, replacement, refund, etc.) as required by EU law for recalled products. Costs of recall (including refunds or repairs and any public notices) are to be borne by Client (except to the extent the recall was solely caused by Festilaw's negligence or breach).</p>
<p>Preventive and Follow-up Actions: Client shall investigate the root cause of the safety issue and implement measures to prevent future occurrences. Client will keep Festilaw informed of investigation findings and corrective steps. If authorities require follow-up reports (e.g. progress of recall, destruction of returned items), Client will provide the necessary information for Festilaw to relay. Client also agrees to cooperate with any "forced" recall actions by authorities, meaning that if, for instance, an authority directly orders certain actions (like public warnings, product seizures, etc.), Client will not obstruct and will actively support those measures.</p>
<p><strong>4.4</strong>&nbsp;&nbsp;Additional Responsibilities and Acknowledgments:</p>
<p>No Illegal Substances: Client warrants that its products do not contain any substances forbidden by EU chemical or safety regulations. For example, Client confirms it does not use materials that violate EU REACH regulations or other directives limiting substances in consumer goods. This warranty is crucial given EU rules on chemical safety in consumer products (such as bans on certain phthalates, heavy metals, or other toxic chemicals in consumer goods). If any component of a product is regulated (for instance, battery restrictions, etc.), Client confirms compliance with those specific rules as well.</p>
<p>Consumer Law Compliance: If Client sells directly to consumers in the EU (via a website or other direct sales), it confirms that it operates in line with EU consumer protection laws. This includes providing clear product information, honoring consumer rights like returns and refunds, and not engaging in unfair or misleading practices. Client acknowledges that failure to comply with consumer protection laws can result in penalties or reputational damage, and affirms that it has systems in place to remain compliant.</p>
<p>Updates on Regulatory Changes: Client is responsible for staying informed of any changes in EU regulations specific to its products (with Festilaw providing reasonable guidance if aware of changes, especially those affecting the Responsible Person role). If a new EU law or standard imposes additional requirements on the products (for example, new labelling, a ban of a certain substance, a new documentation requirement, etc.), Client will take necessary steps to comply and will update Festilaw on how compliance is achieved.</p>
<p>Designated Contacts: Client will designate a primary contact person (and an alternate) who will liaise with Festilaw. These individuals should be empowered to make decisions or quickly obtain decisions within Client in case of an urgent compliance matter. Client will ensure at least one contact is reachable at short notice (within one working day) for any urgent safety communication from Festilaw.</p>

<h2>5. Limitations of Service and Liability</h2>
<p><strong>5.1</strong>&nbsp;&nbsp;Festilaw Not Responsible for Product Defects or Consumer Damages: Festilaw's role is strictly as a compliance representative and point of contact in the EU. The Parties agree that Festilaw is not the manufacturer or importer of the products and does not assume the manufacturer's product liability. Client retains full responsibility for the safety and compliance of the products. Accordingly, Festilaw shall not be held responsible for any damages to property or personal injury (including death) arising from defects or use of Client's products, except to the extent such damage is directly caused by Festilaw's own gross negligence or willful misconduct. This means that if consumers or other third parties bring claims regarding the products (e.g. injury from product use), Client will bear all liability and costs, and if Festilaw is named or implicated due to its role, Client will indemnify Festilaw (see Section 5.3). Festilaw's duties are limited to those of a Responsible Person as per this Agreement and applicable law; Festilaw is not providing general quality control, manufacturing oversight, or insurance against product risks.</p>
<p><strong>5.2</strong>&nbsp;&nbsp;Limitation of Festilaw's Liability: To the fullest extent permitted by law, if Festilaw is found liable to Client for any claim arising out of this Agreement (whether in contract, tort, or otherwise), Festilaw's maximum aggregate liability shall be limited to no more than the amount of the annual fee paid by Client for the current contract year (i.e., the {{ $fee }} € annual fee). Under no circumstances will Festilaw be liable for indirect, consequential or punitive damages, such as lost profits, lost sales, or reputational harm, even if advised of the possibility of such damages. The Parties acknowledge that the annual fee is set in consideration of this liability cap. Festilaw is not an insurer and cannot assume unbounded risk for the nominal service fee. Client accepts that it should maintain appropriate insurance for product liability and other risks as needed.</p>
<p>Rationale: The above limitation is a core condition of Festilaw's agreement to provide services. Both Parties agree that Client's potential recovery for any breach or error by Festilaw is limited and reasonable given the nature of services. In any case, any claim by Client against Festilaw for breach or negligence must be brought within 90 days of Client becoming aware of the event giving rise to the claim, and no later than 1 year from the event. If Client fails to notify Festilaw of a potential claim or issue within 90 days of discovery, it waives its right to claim on that issue. (This 90-day notice requirement ensures timely resolution and that Festilaw can attempt to mitigate any harm.)</p>
<p><strong>5.3</strong>&nbsp;&nbsp;Indemnification: Client agrees to indemnify and hold harmless Festilaw and its directors, employees, and agents against any and all losses, damages, liabilities, fines, penalties, costs, and expenses (including reasonable legal fees) arising out of or in connection with any third-party claims or regulatory actions that relate to Client's products or Client's breach of its obligations. This indemnity covers, for example: if a national authority imposes a fine on Festilaw or takes legal action due to a Client product being unsafe or non-compliant (except if caused by Festilaw's failure to forward information Client had provided), or if a consumer sues Festilaw alleging product injury. Client will step in to assume the defense and will pay any resulting amounts. Client also indemnifies Festilaw for any harm caused by Client's failure to timely provide accurate information (e.g., if Festilaw incurs penalties for missing a reporting deadline because Client delayed or withheld information). Festilaw will promptly notify Client of any claim or action it becomes aware of, and will allow Client to defend it (with Festilaw's reasonable cooperation). This clause survives termination of the Agreement.</p>
<p><strong>5.4</strong>&nbsp;&nbsp;Excluded Services: The Parties acknowledge that Festilaw's Responsible Person service is focused on regulatory compliance support and does not include other product or business consulting services unless otherwise agreed in writing. Unless a separate arrangement is made (or additional hours under Section 3.2 are utilized), Festilaw is not responsible for:</p>
<p>Product Testing or Certification: Festilaw will not test products for safety or compliance, nor obtain certificates (like CE certificates) on Client's behalf. These remain Client's duties (though Festilaw can recommend laboratories or certification bodies if asked).</p>
<p>Comprehensive Label/Packaging Reviews: Festilaw's check of labels is limited to ensuring the presence of required contact info and obvious safety markings. Festilaw is not reviewing artwork, marketing claims, or translations on labels for legal accuracy. Client should engage compliance experts for full label review if needed.</p>
<p>Legal Compliance Outside EU Consumer Safety: Festilaw's role is tied to EU consumer product safety compliance. Other legal areas, for example, data privacy compliance (GDPR), tax/VAT issues, general corporate legal obligations, etc., are outside this Agreement's scope.</p>
<p>Handling Consumer Inquiries or Complaints: Festilaw is not operating a call center or customer service for Client. While Festilaw's contact may appear on products for regulatory reasons, any consumer inquiries received by Festilaw will be forwarded to Client. It is Client's responsibility to respond to consumers (Festilaw can assist in drafting responses regarding safety, if within the included support hours or otherwise billable).</p>
<p>Import/Customs Duties: Festilaw is not acting as the importer of record. Ensuring products get through customs (beyond providing the required Responsible Person information) is up to Client or its logistics providers. If customs authorities contact Festilaw, Festilaw will direct them to Client's import agent.</p>
<p>If Client desires any of the above services from Festilaw, the Parties must negotiate a separate agreement or addendum (with possible additional fees). By clarifying these exclusions, the Parties aim to avoid misunderstandings about the division of responsibilities.</p>

<h2>6. Confidentiality</h2>
<p>Both Parties shall treat as confidential all information received from the other party in connection with this Agreement that is not publicly known. Festilaw shall keep Client's technical documentation, product designs, formulas, sales data, and any other sensitive business information confidential. Festilaw will use such information solely for performing its duties under this Agreement or for compliance with legal obligations (e.g. sharing with an authority if lawfully required). Festilaw will not disclose Client's confidential information to any third party (except authorities or subcontractors bound by confidentiality, if any are used) without Client's prior written consent. Client likewise will keep confidential any non-public information about Festilaw's business or pricing. This confidentiality clause remains in force even after termination of the Agreement.</p>
<p>(Note: In accordance with General Terms Section 2.2.6 and Article 3.1(e) of the Main Agreement, Festilaw retains technical documentation and compliance records for ten (10) years following termination or expiry of the Agreement, as required by its obligations as EU Responsible Person. Documentation will be securely destroyed at the end of that period unless retention is required by law or ongoing regulatory or legal proceedings. Such documentation will not be returned or destroyed upon Client's request after the purpose of use is fulfilled, except that Festilaw may retain copies as required by law or to prove its due diligence as Responsible Person.)</p>

<h2>7. Term and Termination</h2>
<p><strong>7.1</strong>&nbsp;&nbsp;Initial Term: The initial term of this Agreement is one (1) year from the effective date. Thereafter, the Agreement will automatically renew for successive one-year periods under the same terms, unless terminated as per Section 7.2. The annual fee for each renewal term will be as per Section 3 (subject to any adjustment notice given).</p>
<p><strong>7.2</strong>&nbsp;&nbsp;Termination Notice: Either Party may elect not to renew the Agreement at the end of the then-current term by providing at least 60 days' written notice prior to the renewal date. If neither party gives timely notice, the Agreement will renew and both parties will be obliged for the new term. Notice of termination/non-renewal must be given in writing (email is acceptable, provided receipt is confirmed).</p>
<p><strong>7.3</strong>&nbsp;&nbsp;Termination for cause: Either Party may terminate this Agreement with immediate effect before the end of a term if the other party commits a material breach that is either incapable of remedy or is not cured within 14 days of written notice. The following shall be considered material breaches by Client: failure to pay fees when due (subject to a 14-day cure period), repeated failure to provide required information or cooperation per Section 4.2, selling products in violation of EU safety laws (jeopardizing Festilaw legally), or providing false information to Festilaw. Material breaches by Festilaw include: a willful refusal to perform its duties or a pattern of gross negligence in carrying out the Responsible Person obligations. Additionally, if Client undergoes bankruptcy or ceases business, Festilaw may terminate (and vice versa, if Festilaw can no longer legally operate or perform the service, it may terminate). Termination for cause must be stated in writing with reference to the breach.</p>
<p><strong>7.4</strong>&nbsp;&nbsp;Effect of Termination: Upon termination or non-renewal, Festilaw's appointment as Responsible Person ends as of the effective termination date. Client must immediately cease using Festilaw's name/address on any new product labels, websites, or materials. (Client should plan to have a new Responsible Person in place as required by EU law, by the termination date, to avoid sales disruption. Festilaw will cooperate in transferring responsibilities in good faith.) Festilaw will keep copy of records necessary for legal compliance or record-keeping. Any outstanding invoices or fees for services rendered before termination remain payable. Sections 5 (Liability and Indemnity), 6 (Confidentiality), and any other clauses which by their nature should survive, shall survive termination.</p>

<h2>8. Miscellaneous Provisions</h2>
<p><strong>8.1</strong>&nbsp;&nbsp;Governing Law and Jurisdiction: This Agreement shall be governed by and construed in accordance with the laws of the Netherlands. Any disputes arising from or in connection with this Agreement that cannot be resolved amicably shall be submitted to the exclusive jurisdiction of the competent court of Oost-Brabant, location 's-Hertogenbosch, the Netherlands.</p>
<p><strong>8.2</strong>&nbsp;&nbsp;Entire Agreement: This Agreement constitutes the entire understanding between Festilaw and Client regarding the Responsible Person service. It supersedes all prior discussions, proposals, or agreements (whether oral or written) on this subject. Any amendments to this Agreement must be made in writing and signed by both Parties. In case any purchase order or other document from Client contains terms, the terms of this Agreement shall prevail to the extent of any conflict.</p>
<p><strong>8.3</strong>&nbsp;&nbsp;No Assignment: Client may not assign or transfer this Agreement (or any rights/obligations hereunder) to another party without Festilaw's prior written consent, except to a successor entity in the case of a merger or acquisition of Client's business (and with notice to Festilaw). Festilaw may not assign this Agreement without Client's consent, except that Festilaw may subcontract certain administrative tasks to its affiliated offices or qualified compliance subcontractors, provided Festilaw remains fully responsible for the performance of the Agreement.</p>
<p><strong>8.4</strong>&nbsp;&nbsp;No Partnership/Agency: The Parties are independent contractors. Nothing in this Agreement creates a joint venture, partnership, or employment relationship between Festilaw and Client. Client is the manufacturer/seller, and Festilaw is a service provider. Except as expressly stated in this Agreement for regulatory representation purposes, neither party is an agent of the other, and neither can bind the other to any third-party obligation.</p>
<p><strong>8.5</strong>&nbsp;&nbsp;Severability: If any provision of this Agreement is held by a court or authority of competent jurisdiction to be invalid or unenforceable, that provision will be severed and the remainder of the Agreement will remain in full force. The Parties shall negotiate in good faith to replace any invalid provision with a valid provision that closest reflects the original intent and economic effect.</p>
<p><strong>8.6</strong>&nbsp;&nbsp;Waiver: The failure of either Party to enforce any provision or to exercise any right under this Agreement shall not constitute a waiver of that provision or right. Any waiver must be explicit and in writing to be effective and will not apply to any circumstances other than those for which it is given.</p>
<p><strong>8.7</strong>&nbsp;&nbsp;Language: This Agreement is drawn up in the English language at the request of the Parties. All notices, documentation, and communications under this Agreement shall be in English. (Partijen komen uitdrukkelijk overeen dat deze overeenkomst in het Engels is opgesteld.)</p>
<p><strong>8.8</strong>&nbsp;&nbsp;Counterparts &amp; Electronic Signatures: The Agreement may be signed in two counterparts, which together will constitute one instrument. Signatures transmitted by email PDF or via electronic signing platform shall be valid as original signatures.</p>
